// created: 2022-10-24T08:28:52.391Z
// version: 15.0.0
export default [
	// ":"
	// 903 (◌ः) DEVANAGARI SIGN VISARGA (Deva)
	// A83 (◌ઃ) GUJARATI SIGN VISARGA (Gujr)
	0xA4FD, // A4FD (ꓽ) LISU LETTER TONE MYA JEU
	// "."
	// 2E (.) FULL STOP (Zyyy)
	// 10A50 (𐩐) KHAROSHTHI PUNCTUATION DOT (Khar)
	// 660 (٠) ARABIC-INDIC DIGIT ZERO (Arab)
	0xA4F8, // A4F8 (ꓸ) LISU LETTER TONE MYA TI
	// ".."
	// 2E (.) FULL STOP + 2E (.) FULL STOP (Zyyy)
	0xA4FA, // A4FA (ꓺ) LISU LETTER TONE MYA CYA
	// "A"
	// 13AA (Ꭺ) CHEROKEE LETTER GO (Cher)
	// 15C5 (ᗅ) CANADIAN SYLLABICS CARRIER GHO (Cans)
	// 16F40 (𖽀) MIAO LETTER ZZYA (Plrd)
	// 102A0 (𐊠) CARIAN LETTER A (Cari)
	0xA4EE, // A4EE (ꓮ) LISU LETTER A
	// "Ɐ"
	// 15C4 (ᗄ) CANADIAN SYLLABICS CARRIER GHU (Cans)
	0xA4EF, // A4EF (ꓯ) LISU LETTER AE
	// "B"
	// 13F4 (Ᏼ) CHEROKEE LETTER YV (Cher)
	// 15F7 (ᗷ) CANADIAN SYLLABICS CARRIER KHE (Cans)
	// 10282 (𐊂) LYCIAN LETTER B (Lyci)
	// 102A1 (𐊡) CARIAN LETTER P2 (Cari)
	// 10301 (𐌁) OLD ITALIC LETTER BE (Ital)
	0xA4D0, // A4D0 (ꓐ) LISU LETTER BA
	// "C"
	// 118F2 (𑣲) WARANG CITI NUMBER NINETY (Wara)
	// 118E9 (𑣩) WARANG CITI DIGIT NINE (Wara)
	// 13DF (Ꮯ) CHEROKEE LETTER TLI (Cher)
	// 102A2 (𐊢) CARIAN LETTER D (Cari)
	// 10302 (𐌂) OLD ITALIC LETTER KE (Ital)
	// 1051C (𐔜) ELBASAN LETTER SHE (Elba)
	0xA4DA, // A4DA (ꓚ) LISU LETTER CA
	// "d"
	// 64 (d) LATIN SMALL LETTER D (Latn)
	// 13E7 (Ꮷ) CHEROKEE LETTER TSU (Cher)
	// 146F (ᑯ) CANADIAN SYLLABICS KO (Cans)
	0xA4D2, // A4D2 (ꓒ) LISU LETTER PHA
	// "D"
	// 13A0 (Ꭰ) CHEROKEE LETTER A (Cher)
	// 15DE (ᗞ) CANADIAN SYLLABICS CARRIER THE (Cans)
	// 15EA (ᗪ) CANADIAN SYLLABICS CARRIER PE (Cans)
	0xA4D3, // A4D3 (ꓓ) LISU LETTER DA
	// "E"
	// 2D39 (ⴹ) TIFINAGH LETTER YADD (Tfng)
	// 13AC (Ꭼ) CHEROKEE LETTER GV (Cher)
	// 10286 (𐊆) LYCIAN LETTER I (Lyci)
	0xA4F0, // A4F0 (ꓰ) LISU LETTER E
	// "Ǝ"
	// 2D3A (ⴺ) TIFINAGH LETTER YADDH (Tfng)
	0xA4F1, // A4F1 (ꓱ) LISU LETTER EU
	// "F"
	// 15B4 (ᖴ) CANADIAN SYLLABICS BLACKFOOT WE (Cans)
	// 118C2 (𑣂) WARANG CITI SMALL LETTER WI (Wara)
	// 10287 (𐊇) LYCIAN LETTER W (Lyci)
	// 102A5 (𐊥) CARIAN LETTER R (Cari)
	// 10525 (𐔥) ELBASAN LETTER GHE (Elba)
	0xA4DD, // A4DD (ꓝ) LISU LETTER TSA
	// "Ⅎ"
	// 15B5 (ᖵ) CANADIAN SYLLABICS BLACKFOOT WI (Cans)
	0xA4DE, // A4DE (ꓞ) LISU LETTER TSHA
	// "G"
	// 13C0 (Ꮐ) CHEROKEE LETTER NAH (Cher)
	// 13F3 (Ᏻ) CHEROKEE LETTER YU (Cher)
	0xA4D6, // A4D6 (ꓖ) LISU LETTER GA
	// "H"
	// 13BB (Ꮋ) CHEROKEE LETTER MI (Cher)
	// 157C (ᕼ) CANADIAN SYLLABICS NUNAVUT H (Cans)
	// 102CF (𐋏) CARIAN LETTER E2 (Cari)
	0xA4E7, // A4E7 (ꓧ) LISU LETTER XA
	// "J"
	// 13AB (Ꭻ) CHEROKEE LETTER GU (Cher)
	// 148D (ᒍ) CANADIAN SYLLABICS CO (Cans)
	0xA4D9, // A4D9 (ꓙ) LISU LETTER JA
	// "K"
	// 13E6 (Ꮶ) CHEROKEE LETTER TSO (Cher)
	// 16D5 (ᛕ) RUNIC LETTER OPEN-P (Runr)
	// 10518 (𐔘) ELBASAN LETTER QE (Elba)
	0xA4D7, // A4D7 (ꓗ) LISU LETTER KA
	// "l"
	// 6C (l) LATIN SMALL LETTER L (Latn)
	// 23FD (⏽) POWER ON SYMBOL (Zyyy)
	// 31 (1) DIGIT ONE (Zyyy)
	// 661 (١) ARABIC-INDIC DIGIT ONE (Arab)
	// 10320 (𐌠) OLD ITALIC NUMERAL ONE (Ital)
	// 1E8C7 (𞣇) MENDE KIKAKUI DIGIT ONE (Mend)
	// 5D5 (ו) HEBREW LETTER VAV (Hebr)
	// 5DF (ן) HEBREW LETTER FINAL NUN (Hebr)
	// 627 (ا) ARABIC LETTER ALEF (Arab)
	// 7CA (ߊ) NKO LETTER A (Nkoo)
	// 2D4F (ⵏ) TIFINAGH LETTER YAN (Tfng)
	// 16C1 (ᛁ) RUNIC LETTER ISAZ IS ISS I (Runr)
	// 16F28 (𖼨) MIAO LETTER GHA (Plrd)
	// 1028A (𐊊) LYCIAN LETTER J (Lyci)
	// 10309 (𐌉) OLD ITALIC LETTER I (Ital)
	0xA4F2, // A4F2 (ꓲ) LISU LETTER I
	// "L"
	// 13DE (Ꮮ) CHEROKEE LETTER TLE (Cher)
	// 14AA (ᒪ) CANADIAN SYLLABICS MA (Cans)
	// 16F16 (𖼖) MIAO LETTER LA (Plrd)
	// 10526 (𐔦) ELBASAN LETTER GHAMMA (Elba)
	0xA4E1, // A4E1 (ꓡ) LISU LETTER LA
	// "M"
	// 13B7 (Ꮇ) CHEROKEE LETTER LU (Cher)
	// 15F0 (ᗰ) CANADIAN SYLLABICS CARRIER GO (Cans)
	// 16D6 (ᛖ) RUNIC LETTER EHWAZ EH E (Runr)
	// 102B0 (𐊰) CARIAN LETTER S (Cari)
	// 10311 (𐌑) OLD ITALIC LETTER SHE (Ital)
	0xA4DF, // A4DF (ꓟ) LISU LETTER MA
	// "N"
	// 10513 (𐔓) ELBASAN LETTER NE (Elba)
	0xA4E0, // A4E0 (ꓠ) LISU LETTER NA
	// "O"
	// 30 (0) DIGIT ZERO (Zyyy)
	// 7C0 (߀) NKO DIGIT ZERO (Nkoo)
	// 9E6 (০) BENGALI DIGIT ZERO (Beng)
	// B66 (୦) ORIYA DIGIT ZERO (Orya)
	// 3007 (〇) IDEOGRAPHIC NUMBER ZERO (Hani)
	// 114D0 (𑓐) TIRHUTA DIGIT ZERO (Tirh)
	// 118E0 (𑣠) WARANG CITI DIGIT ZERO (Wara)
	// 2D54 (ⵔ) TIFINAGH LETTER YAR (Tfng)
	// 12D0 (ዐ) ETHIOPIC SYLLABLE PHARYNGEAL A (Ethi)
	// B20 (ଠ) ORIYA LETTER TTHA (Orya)
	// 10292 (𐊒) LYCIAN LETTER U (Lyci)
	// 102AB (𐊫) CARIAN LETTER O (Cari)
	// 10516 (𐔖) ELBASAN LETTER O (Elba)
	0xA4F3, // A4F3 (ꓳ) LISU LETTER O
	// "P"
	// 13E2 (Ꮲ) CHEROKEE LETTER TLV (Cher)
	// 146D (ᑭ) CANADIAN SYLLABICS KI (Cans)
	// 10295 (𐊕) LYCIAN LETTER R (Lyci)
	0xA4D1, // A4D1 (ꓑ) LISU LETTER PA
	// "R"
	// 13A1 (Ꭱ) CHEROKEE LETTER E (Cher)
	// 13D2 (Ꮢ) CHEROKEE LETTER SV (Cher)
	// 1587 (ᖇ) CANADIAN SYLLABICS TLHI (Cans)
	// 16F35 (𖼵) MIAO LETTER ZHA (Plrd)
	0xA4E3, // A4E3 (ꓣ) LISU LETTER ZHA
	// "S"
	// 13D5 (Ꮥ) CHEROKEE LETTER DE (Cher)
	// 13DA (Ꮪ) CHEROKEE LETTER DU (Cher)
	// 16F3A (𖼺) MIAO LETTER SA (Plrd)
	// 10296 (𐊖) LYCIAN LETTER S (Lyci)
	0xA4E2, // A4E2 (ꓢ) LISU LETTER SA
	// "T"
	// 13A2 (Ꭲ) CHEROKEE LETTER I (Cher)
	// 16F0A (𖼊) MIAO LETTER TA (Plrd)
	// 10297 (𐊗) LYCIAN LETTER T (Lyci)
	// 102B1 (𐊱) CARIAN LETTER C-18 (Cari)
	// 10315 (𐌕) OLD ITALIC LETTER TE (Ital)
	0xA4D4, // A4D4 (ꓔ) LISU LETTER TA
	// "U"
	// 1200 (ሀ) ETHIOPIC SYLLABLE HA (Ethi)
	// 144C (ᑌ) CANADIAN SYLLABICS TE (Cans)
	// 16F42 (𖽂) MIAO LETTER WA (Plrd)
	0xA4F4, // A4F4 (ꓴ) LISU LETTER U
	// "V"
	// 667 (٧) ARABIC-INDIC DIGIT SEVEN (Arab)
	// 2D38 (ⴸ) TIFINAGH LETTER YADH (Tfng)
	// 13D9 (Ꮩ) CHEROKEE LETTER DO (Cher)
	// 142F (ᐯ) CANADIAN SYLLABICS PE (Cans)
	// A6DF (ꛟ) BAMUM LETTER KO (Bamu)
	// 16F08 (𖼈) MIAO LETTER VA (Plrd)
	// 1051D (𐔝) ELBASAN LETTER TE (Elba)
	0xA4E6, // A4E6 (ꓦ) LISU LETTER HA
	// "Ʌ"
	// 668 (٨) ARABIC-INDIC DIGIT EIGHT (Arab)
	// 2D37 (ⴷ) TIFINAGH LETTER YAD (Tfng)
	// 1431 (ᐱ) CANADIAN SYLLABICS PI (Cans)
	// A6CE (ꛎ) BAMUM LETTER MI (Bamu)
	// 16F3D (𖼽) MIAO LETTER ZZA (Plrd)
	// 1028D (𐊍) LYCIAN LETTER L (Lyci)
	0xA4E5, // A4E5 (ꓥ) LISU LETTER NGA
	// "W"
	// 118EF (𑣯) WARANG CITI NUMBER SIXTY (Wara)
	// 118E6 (𑣦) WARANG CITI DIGIT SIX (Wara)
	// 13B3 (Ꮃ) CHEROKEE LETTER LA (Cher)
	// 13D4 (Ꮤ) CHEROKEE LETTER TA (Cher)
	0xA4EA, // A4EA (ꓪ) LISU LETTER WA
	// "X"
	// 166D (᙭) CANADIAN SYLLABICS CHI SIGN (Cans)
	// 10322 (𐌢) OLD ITALIC NUMERAL TEN (Ital)
	// 118EC (𑣬) WARANG CITI NUMBER THIRTY (Wara)
	// 2D5D (ⵝ) TIFINAGH LETTER YATH (Tfng)
	// 16B7 (ᚷ) RUNIC LETTER GEBO GYFU G (Runr)
	// 10290 (𐊐) LYCIAN LETTER MM (Lyci)
	// 102B4 (𐊴) CARIAN LETTER X (Cari)
	// 10317 (𐌗) OLD ITALIC LETTER EKS (Ital)
	// 10527 (𐔧) ELBASAN LETTER KHE (Elba)
	0xA4EB, // A4EB (ꓫ) LISU LETTER SHA
	// "Y"
	// 13A9 (Ꭹ) CHEROKEE LETTER GI (Cher)
	// 13BD (Ꮍ) CHEROKEE LETTER MU (Cher)
	// 16F43 (𖽃) MIAO LETTER AH (Plrd)
	// 102B2 (𐊲) CARIAN LETTER U (Cari)
	0xA4EC, // A4EC (ꓬ) LISU LETTER YA
	// "Z"
	// 118E5 (𑣥) WARANG CITI DIGIT FIVE (Wara)
	// 13C3 (Ꮓ) CHEROKEE LETTER NO (Cher)
	0xA4DC, // A4DC (ꓜ) LISU LETTER DZA
	// "Ո"
	// 1260 (በ) ETHIOPIC SYLLABLE BA (Ethi)
	// 144E (ᑎ) CANADIAN SYLLABICS TI (Cans)
	0xA4F5, // A4F5 (ꓵ) LISU LETTER UE
	// "ᗡ"
	// 15E1 (ᗡ) CANADIAN SYLLABICS CARRIER THA (Cans)
	0xA4F7, // A4F7 (ꓷ) LISU LETTER OE
	// "ᙠ"
	// 1660 (ᙠ) CANADIAN SYLLABICS CARRIER TSA (Cans)
	0xA4ED, // A4ED (ꓭ) LISU LETTER GHA
]