export default [

	0x13CE, // (Ꮞ) CHEROKEE LETTER SE
	0x13EE, // (Ꮾ) CHEROKEE LETTER WV

	0x13CF, // (Ꮟ) CHEROKEE LETTER SI
	0x13E7, // (Ꮷ) CHEROKEE LETTER TSU
	0x13C2, // (Ꮒ) CHEROKEE LETTER NI
	0x13A5, // (Ꭵ) CHEROKEE LETTER V
	0x13A9, // (Ꭹ) CHEROKEE LETTER GI
	
];