// created: 2022-10-24T08:28:52.696Z
// version: 15.0.0
export default [
	// "́"
	// 59C (◌֜) HEBREW ACCENT GERESH (Hebr)
	// 59D (◌֝) HEBREW ACCENT GERESH MUQDAM (Hebr)
	// 618 (◌ؘ) ARABIC SMALL FATHA (Arab)
	// 64E (◌َ) ARABIC FATHA (Arab)
	0x747, // 747 (◌݇) SYRIAC OBLIQUE LINE ABOVE
	// "̇"
	// 5C4 (◌ׄ) HEBREW MARK UPPER DOT (Hebr)
	// 6EC (◌۬) ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE (Arab)
	// 8EA (◌࣪) ARABIC TONE ONE DOT ABOVE (Arab)
	// 5B9 (◌ֹ) HEBREW POINT HOLAM (Hebr)
	// 5BA (◌ֺ) HEBREW POINT HOLAM HASER FOR VAV (Hebr)
	// 5C2 (◌ׂ) HEBREW POINT SIN DOT (Hebr)
	// 5C1 (◌ׁ) HEBREW POINT SHIN DOT (Hebr)
	// 7ED (◌߭) NKO COMBINING SHORT RISING TONE (Nkoo)
	// 902 (◌ं) DEVANAGARI SIGN ANUSVARA (Deva)
	// A02 (◌ਂ) GURMUKHI SIGN BINDI (Guru)
	// A82 (◌ં) GUJARATI SIGN ANUSVARA (Gujr)
	// BCD (◌்) TAMIL SIGN VIRAMA (Taml)
	0x740, // 740 (◌݀) SYRIAC FEMININE DOT
	0x741, // 741 (◌݁) SYRIAC QUSHSHAYA
]