export default [
	// computed: 2022-10-15T05:22:41.091Z
	// version: 15.0.0
	// "a"
	// 61 (a) LATIN SMALL LETTER A (Latn)
	0x3B1, // 3B1 (α) GREEK SMALL LETTER ALPHA
	// "i"
	// 69 (i) LATIN SMALL LETTER I (Latn)
	0x3B9, // 3B9 (ι) GREEK SMALL LETTER IOTA
	// "j"
	// 6A (j) LATIN SMALL LETTER J (Latn)
	0x3F3, // 3F3 (ϳ) GREEK LETTER YOT
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	0x3BF, // 3BF (ο) GREEK SMALL LETTER OMICRON
	0x3C3, // 3C3 (σ) GREEK SMALL LETTER SIGMA
	// "p"
	// 70 (p) LATIN SMALL LETTER P (Latn)
	0x3C1, // 3C1 (ρ) GREEK SMALL LETTER RHO
	// "r"
	// 72 (r) LATIN SMALL LETTER R (Latn)
	0x1D26, // 1D26 (ᴦ) GREEK LETTER SMALL CAPITAL GAMMA
	// "ß"
	// DF (ß) LATIN SMALL LETTER SHARP S (Latn)
	0x3B2, // 3B2 (β) GREEK SMALL LETTER BETA
	// "u"
	// 75 (u) LATIN SMALL LETTER U (Latn)
	0x3C5, // 3C5 (υ) GREEK SMALL LETTER UPSILON
	// "v"
	// 76 (v) LATIN SMALL LETTER V (Latn)
	0x3BD, // 3BD (ν) GREEK SMALL LETTER NU
	// "y"
	// 79 (y) LATIN SMALL LETTER Y (Latn)
	0x3B3, // 3B3 (γ) GREEK SMALL LETTER GAMMA
]