// created: 2022-10-24T08:28:54.740Z
// version: 15.0.0
export default [
	// "̣"
	// 8ED (◌࣭) ARABIC TONE ONE DOT BELOW (Arab)
	// 5B4 (◌ִ) HEBREW POINT HIRIQ (Hebr)
	// 65C (◌ٜ) ARABIC VOWEL SIGN DOT BELOW (Arab)
	// 93C (◌़) DEVANAGARI SIGN NUKTA (Deva)
	// 9BC (◌়) BENGALI SIGN NUKTA (Beng)
	// A3C (◌਼) GURMUKHI SIGN NUKTA (Guru)
	// ABC (◌઼) GUJARATI SIGN NUKTA (Gujr)
	// B3C (◌଼) ORIYA SIGN NUKTA (Orya)
	// 114C3 (◌𑓃) TIRHUTA SIGN NUKTA (Tirh)
	// 10A3A (◌𐨺) KHAROSHTHI SIGN DOT BELOW (Khar)
	0x111CA, // 111CA (◌𑇊) SHARADA SIGN NUKTA
	// "॰"
	// 970 (॰) DEVANAGARI ABBREVIATION SIGN (Deva)
	// AF0 (૰) GUJARATI ABBREVIATION SIGN (Gujr)
	// 110BB (𑂻) KAITHI ABBREVIATION SIGN (Kthi)
	0x111C7, // 111C7 (𑇇) SHARADA ABBREVIATION SIGN
	// "ऺ"
	// 93A (◌ऺ) DEVANAGARI VOWEL SIGN OE (Deva)
	0x111CB, // 111CB (◌𑇋) SHARADA VOWEL MODIFIER MARK
]