// created: 2022-10-24T08:28:51.817Z
// version: 15.0.0
export default [
	// "̆̇"
	// 6E8 (◌ۨ) ARABIC SMALL HIGH NOON (Arab)
	// 901 (◌ँ) DEVANAGARI SIGN CANDRABINDU (Deva)
	// 981 (◌ঁ) BENGALI SIGN CANDRABINDU (Beng)
	// B01 (◌ଁ) ORIYA SIGN CANDRABINDU (Orya)
	// 114BF (◌𑒿) TIRHUTA SIGN CANDRABINDU (Tirh)
	0xA81, // A81 (◌ઁ) GUJARATI SIGN CANDRABINDU
	// "̇"
	// 5C4 (◌ׄ) HEBREW MARK UPPER DOT (Hebr)
	// 6EC (◌۬) ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE (Arab)
	// 740 (◌݀) SYRIAC FEMININE DOT (Syrc)
	// 8EA (◌࣪) ARABIC TONE ONE DOT ABOVE (Arab)
	// 741 (◌݁) SYRIAC QUSHSHAYA (Syrc)
	// 5B9 (◌ֹ) HEBREW POINT HOLAM (Hebr)
	// 5BA (◌ֺ) HEBREW POINT HOLAM HASER FOR VAV (Hebr)
	// 5C2 (◌ׂ) HEBREW POINT SIN DOT (Hebr)
	// 5C1 (◌ׁ) HEBREW POINT SHIN DOT (Hebr)
	// 7ED (◌߭) NKO COMBINING SHORT RISING TONE (Nkoo)
	// 902 (◌ं) DEVANAGARI SIGN ANUSVARA (Deva)
	// A02 (◌ਂ) GURMUKHI SIGN BINDI (Guru)
	// BCD (◌்) TAMIL SIGN VIRAMA (Taml)
	0xA82, // A82 (◌ં) GUJARATI SIGN ANUSVARA
	// "̣"
	// 8ED (◌࣭) ARABIC TONE ONE DOT BELOW (Arab)
	// 5B4 (◌ִ) HEBREW POINT HIRIQ (Hebr)
	// 65C (◌ٜ) ARABIC VOWEL SIGN DOT BELOW (Arab)
	// 93C (◌़) DEVANAGARI SIGN NUKTA (Deva)
	// 9BC (◌়) BENGALI SIGN NUKTA (Beng)
	// A3C (◌਼) GURMUKHI SIGN NUKTA (Guru)
	// B3C (◌଼) ORIYA SIGN NUKTA (Orya)
	// 111CA (◌𑇊) SHARADA SIGN NUKTA (Shrd)
	// 114C3 (◌𑓃) TIRHUTA SIGN NUKTA (Tirh)
	// 10A3A (◌𐨺) KHAROSHTHI SIGN DOT BELOW (Khar)
	0xABC, // ABC (◌઼) GUJARATI SIGN NUKTA
	// ":"
	// 903 (◌ः) DEVANAGARI SIGN VISARGA (Deva)
	// A4FD (ꓽ) LISU LETTER TONE MYA JEU (Lisu)
	0xA83, // A83 (◌ઃ) GUJARATI SIGN VISARGA
	// "॰"
	// 970 (॰) DEVANAGARI ABBREVIATION SIGN (Deva)
	// 110BB (𑂻) KAITHI ABBREVIATION SIGN (Kthi)
	// 111C7 (𑇇) SHARADA ABBREVIATION SIGN (Shrd)
	0xAF0, // AF0 (૰) GUJARATI ABBREVIATION SIGN
	// "२"
	// 968 (२) DEVANAGARI DIGIT TWO (Deva)
	0xAE8, // AE8 (૨) GUJARATI DIGIT TWO
	// "३"
	// 969 (३) DEVANAGARI DIGIT THREE (Deva)
	0xAE9, // AE9 (૩) GUJARATI DIGIT THREE
	// "४"
	// 96A (४) DEVANAGARI DIGIT FOUR (Deva)
	0xAEA, // AEA (૪) GUJARATI DIGIT FOUR
	// "८"
	// 96E (८) DEVANAGARI DIGIT EIGHT (Deva)
	0xAEE, // AEE (૮) GUJARATI DIGIT EIGHT
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// C02 (◌ం) TELUGU SIGN ANUSVARA (Telu)
	// C82 (◌ಂ) KANNADA SIGN ANUSVARA (Knda)
	// D02 (◌ം) MALAYALAM SIGN ANUSVARA (Mlym)
	// D82 (◌ං) SINHALA SIGN ANUSVARAYA (Sinh)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// A66 (੦) GURMUKHI DIGIT ZERO (Guru)
	// BE6 (௦) TAMIL DIGIT ZERO (Taml)
	// C66 (౦) TELUGU DIGIT ZERO (Telu)
	// CE6 (೦) KANNADA DIGIT ZERO (Knda)
	// D66 (൦) MALAYALAM DIGIT ZERO (Mlym)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// ED0 (໐) LAO DIGIT ZERO (Laoo)
	// 1040 (၀) MYANMAR DIGIT ZERO (Mymr)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 2C9F (ⲟ) COPTIC SMALL LETTER O (Copt)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 10FF (ჿ) GEORGIAN LETTER LABIAL SIGN (Geor)
	// 585 (օ) ARMENIAN SMALL LETTER OH (Armn)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	// D20 (ഠ) MALAYALAM LETTER TTHA (Mlym)
	// 101D (ဝ) MYANMAR LETTER WA (Mymr)
	// 104EA (𐓪) OSAGE SMALL LETTER O (Osge)
	// 118C8 (𑣈) WARANG CITI SMALL LETTER E (Wara)
	// 118D7 (𑣗) WARANG CITI SMALL LETTER BU (Wara)
	// 1042C (𐐬) DESERET SMALL LETTER LONG O (Dsrt)
	0xAE6, // AE6 (૦) GUJARATI DIGIT ZERO
	// "ऽ"
	// 93D (ऽ) DEVANAGARI SIGN AVAGRAHA (Deva)
	0xABD, // ABD (ઽ) GUJARATI SIGN AVAGRAHA
	// "ु"
	// 941 (◌ु) DEVANAGARI VOWEL SIGN U (Deva)
	0xAC1, // AC1 (◌ુ) GUJARATI VOWEL SIGN U
	// "ू"
	// 942 (◌ू) DEVANAGARI VOWEL SIGN UU (Deva)
	0xAC2, // AC2 (◌ૂ) GUJARATI VOWEL SIGN UU
	// "्"
	// 94D (◌्) DEVANAGARI SIGN VIRAMA (Deva)
	// A4D (◌੍) GURMUKHI SIGN VIRAMA (Guru)
	0xACD, // ACD (◌્) GUJARATI SIGN VIRAMA
]