// created: 2022-10-24T08:28:51.570Z
// version: 15.0.0
export default [
	// "̊"
	// 5AF (◌֯) HEBREW MARK MASORA CIRCLE (Hebr)
	// 6DF (◌۟) ARABIC SMALL HIGH ROUNDED ZERO (Arab)
	// 652 (◌ْ) ARABIC SUKUN (Arab)
	// 1036 (◌ံ) MYANMAR SIGN ANUSVARA (Mymr)
	// 17C6 (◌ំ) KHMER SIGN NIKAHIT (Khmr)
	// 11300 (◌𑌀) GRANTHA SIGN COMBINING ANUSVARA ABOVE (Gran)
	// E4D (◌ํ) THAI CHARACTER NIKHAHIT (Thai)
	// ECD (◌ໍ) LAO NIGGAHITA (Laoo)
	0xB82, // B82 (◌ஂ) TAMIL SIGN ANUSVARA
	// "̇"
	// 5C4 (◌ׄ) HEBREW MARK UPPER DOT (Hebr)
	// 6EC (◌۬) ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE (Arab)
	// 740 (◌݀) SYRIAC FEMININE DOT (Syrc)
	// 8EA (◌࣪) ARABIC TONE ONE DOT ABOVE (Arab)
	// 741 (◌݁) SYRIAC QUSHSHAYA (Syrc)
	// 5B9 (◌ֹ) HEBREW POINT HOLAM (Hebr)
	// 5BA (◌ֺ) HEBREW POINT HOLAM HASER FOR VAV (Hebr)
	// 5C2 (◌ׂ) HEBREW POINT SIN DOT (Hebr)
	// 5C1 (◌ׁ) HEBREW POINT SHIN DOT (Hebr)
	// 7ED (◌߭) NKO COMBINING SHORT RISING TONE (Nkoo)
	// 902 (◌ं) DEVANAGARI SIGN ANUSVARA (Deva)
	// A02 (◌ਂ) GURMUKHI SIGN BINDI (Guru)
	// A82 (◌ં) GUJARATI SIGN ANUSVARA (Gujr)
	0xBCD, // BCD (◌்) TAMIL SIGN VIRAMA
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// C02 (◌ం) TELUGU SIGN ANUSVARA (Telu)
	// C82 (◌ಂ) KANNADA SIGN ANUSVARA (Knda)
	// D02 (◌ം) MALAYALAM SIGN ANUSVARA (Mlym)
	// D82 (◌ං) SINHALA SIGN ANUSVARAYA (Sinh)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// A66 (੦) GURMUKHI DIGIT ZERO (Guru)
	// AE6 (૦) GUJARATI DIGIT ZERO (Gujr)
	// C66 (౦) TELUGU DIGIT ZERO (Telu)
	// CE6 (೦) KANNADA DIGIT ZERO (Knda)
	// D66 (൦) MALAYALAM DIGIT ZERO (Mlym)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// ED0 (໐) LAO DIGIT ZERO (Laoo)
	// 1040 (၀) MYANMAR DIGIT ZERO (Mymr)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 2C9F (ⲟ) COPTIC SMALL LETTER O (Copt)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 10FF (ჿ) GEORGIAN LETTER LABIAL SIGN (Geor)
	// 585 (օ) ARMENIAN SMALL LETTER OH (Armn)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	// D20 (ഠ) MALAYALAM LETTER TTHA (Mlym)
	// 101D (ဝ) MYANMAR LETTER WA (Mymr)
	// 104EA (𐓪) OSAGE SMALL LETTER O (Osge)
	// 118C8 (𑣈) WARANG CITI SMALL LETTER E (Wara)
	// 118D7 (𑣗) WARANG CITI SMALL LETTER BU (Wara)
	// 1042C (𐐬) DESERET SMALL LETTER LONG O (Dsrt)
	0xBE6, // BE6 (௦) TAMIL DIGIT ZERO
	// "உ"
	// D09 (ഉ) MALAYALAM LETTER U (Mlym)
	0xBE8, // BE8 (௨) TAMIL DIGIT TWO
	// "ஐ"
	// D1C (ജ) MALAYALAM LETTER JA (Mlym)
	0xB9C, // B9C (ஜ) TAMIL LETTER JA
]