// created: 2022-10-24T08:28:53.280Z
// version: 15.0.0
export default [
	// "c"
	// 63 (c) LATIN SMALL LETTER C (Latn)
	// 2CA5 (ⲥ) COPTIC SMALL LETTER SIMA (Copt)
	// 441 (с) CYRILLIC SMALL LETTER ES (Cyrl)
	0x1043D, // 1043D (𐐽) DESERET SMALL LETTER CHEE
	// "ꞓ"
	// 3B5 (ε) GREEK SMALL LETTER EPSILON (Grek)
	// 2C89 (ⲉ) COPTIC SMALL LETTER EIE (Copt)
	// 454 (є) CYRILLIC SMALL LETTER UKRAINIAN IE (Cyrl)
	// 511 (ԑ) CYRILLIC SMALL LETTER REVERSED ZE (Cyrl)
	// 118CE (𑣎) WARANG CITI SMALL LETTER YUJ (Wara)
	0x10429, // 10429 (𐐩) DESERET SMALL LETTER LONG E
	// "ʟ"
	// 2CD1 (ⳑ) COPTIC SMALL LETTER L-SHAPED HA (Copt)
	0x10443, // 10443 (𐑃) DESERET SMALL LETTER ETH
	// "ᴎ"
	// 438 (и) CYRILLIC SMALL LETTER I (Cyrl)
	0x1044D, // 1044D (𐑍) DESERET SMALL LETTER ENG
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// C02 (◌ం) TELUGU SIGN ANUSVARA (Telu)
	// C82 (◌ಂ) KANNADA SIGN ANUSVARA (Knda)
	// D02 (◌ം) MALAYALAM SIGN ANUSVARA (Mlym)
	// D82 (◌ං) SINHALA SIGN ANUSVARAYA (Sinh)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// A66 (੦) GURMUKHI DIGIT ZERO (Guru)
	// AE6 (૦) GUJARATI DIGIT ZERO (Gujr)
	// BE6 (௦) TAMIL DIGIT ZERO (Taml)
	// C66 (౦) TELUGU DIGIT ZERO (Telu)
	// CE6 (೦) KANNADA DIGIT ZERO (Knda)
	// D66 (൦) MALAYALAM DIGIT ZERO (Mlym)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// ED0 (໐) LAO DIGIT ZERO (Laoo)
	// 1040 (၀) MYANMAR DIGIT ZERO (Mymr)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 2C9F (ⲟ) COPTIC SMALL LETTER O (Copt)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 10FF (ჿ) GEORGIAN LETTER LABIAL SIGN (Geor)
	// 585 (օ) ARMENIAN SMALL LETTER OH (Armn)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	// D20 (ഠ) MALAYALAM LETTER TTHA (Mlym)
	// 101D (ဝ) MYANMAR LETTER WA (Mymr)
	// 104EA (𐓪) OSAGE SMALL LETTER O (Osge)
	// 118C8 (𑣈) WARANG CITI SMALL LETTER E (Wara)
	// 118D7 (𑣗) WARANG CITI SMALL LETTER BU (Wara)
	0x1042C, // 1042C (𐐬) DESERET SMALL LETTER LONG O
	// "s"
	// 73 (s) LATIN SMALL LETTER S (Latn)
	// 455 (ѕ) CYRILLIC SMALL LETTER DZE (Cyrl)
	// 118C1 (𑣁) WARANG CITI SMALL LETTER A (Wara)
	0x10448, // 10448 (𐑈) DESERET SMALL LETTER ZHEE
]