// created: 2022-10-24T08:28:51.510Z
// version: 15.0.0
export default [
	// "8"
	// 38 (8) DIGIT EIGHT (Zyyy)
	// B03 (◌ଃ) ORIYA SIGN VISARGA (Orya)
	// A6A (੪) GURMUKHI DIGIT FOUR (Guru)
	// 1E8CB (𞣋) MENDE KIKAKUI DIGIT FIVE (Mend)
	// 1031A (𐌚) OLD ITALIC LETTER EF (Ital)
	0x9EA, // 9EA (৪) BENGALI DIGIT FOUR
	// "9"
	// 39 (9) DIGIT NINE (Zyyy)
	// A67 (੧) GURMUKHI DIGIT ONE (Guru)
	// B68 (୨) ORIYA DIGIT TWO (Orya)
	// D6D (൭) MALAYALAM DIGIT SEVEN (Mlym)
	// 118CC (𑣌) WARANG CITI SMALL LETTER KO (Wara)
	// 118D6 (𑣖) WARANG CITI SMALL LETTER AM (Wara)
	0x9ED, // 9ED (৭) BENGALI DIGIT SEVEN
	// "̆̇"
	// 6E8 (◌ۨ) ARABIC SMALL HIGH NOON (Arab)
	// 901 (◌ँ) DEVANAGARI SIGN CANDRABINDU (Deva)
	// A81 (◌ઁ) GUJARATI SIGN CANDRABINDU (Gujr)
	// B01 (◌ଁ) ORIYA SIGN CANDRABINDU (Orya)
	// 114BF (◌𑒿) TIRHUTA SIGN CANDRABINDU (Tirh)
	0x981, // 981 (◌ঁ) BENGALI SIGN CANDRABINDU
	// "̣"
	// 8ED (◌࣭) ARABIC TONE ONE DOT BELOW (Arab)
	// 5B4 (◌ִ) HEBREW POINT HIRIQ (Hebr)
	// 65C (◌ٜ) ARABIC VOWEL SIGN DOT BELOW (Arab)
	// 93C (◌़) DEVANAGARI SIGN NUKTA (Deva)
	// A3C (◌਼) GURMUKHI SIGN NUKTA (Guru)
	// ABC (◌઼) GUJARATI SIGN NUKTA (Gujr)
	// B3C (◌଼) ORIYA SIGN NUKTA (Orya)
	// 111CA (◌𑇊) SHARADA SIGN NUKTA (Shrd)
	// 114C3 (◌𑓃) TIRHUTA SIGN NUKTA (Tirh)
	// 10A3A (◌𐨺) KHAROSHTHI SIGN DOT BELOW (Khar)
	0x9BC, // 9BC (◌়) BENGALI SIGN NUKTA
	// "O"
	// 30 (0) DIGIT ZERO (Zyyy)
	// 7C0 (߀) NKO DIGIT ZERO (Nkoo)
	// B66 (୦) ORIYA DIGIT ZERO (Orya)
	// 3007 (〇) IDEOGRAPHIC NUMBER ZERO (Hani)
	// 114D0 (𑓐) TIRHUTA DIGIT ZERO (Tirh)
	// 118E0 (𑣠) WARANG CITI DIGIT ZERO (Wara)
	// 2D54 (ⵔ) TIFINAGH LETTER YAR (Tfng)
	// 12D0 (ዐ) ETHIOPIC SYLLABLE PHARYNGEAL A (Ethi)
	// B20 (ଠ) ORIYA LETTER TTHA (Orya)
	// A4F3 (ꓳ) LISU LETTER O (Lisu)
	// 10292 (𐊒) LYCIAN LETTER U (Lyci)
	// 102AB (𐊫) CARIAN LETTER O (Cari)
	// 10516 (𐔖) ELBASAN LETTER O (Elba)
	0x9E6, // 9E6 (০) BENGALI DIGIT ZERO
]