// created: 2022-10-24T08:28:51.859Z
// version: 15.0.0
export default [
	// "ঃ"
	// 983 (◌ঃ) BENGALI SIGN VISARGA (Beng)
	// A03 (◌ਃ) GURMUKHI SIGN VISARGA (Guru)
	// C83 (◌ಃ) KANNADA SIGN VISARGA (Knda)
	// D03 (◌ഃ) MALAYALAM SIGN VISARGA (Mlym)
	// D83 (◌ඃ) SINHALA SIGN VISARGAYA (Sinh)
	// 1038 (◌း) MYANMAR SIGN VISARGA (Mymr)
	// 114C1 (◌𑓁) TIRHUTA SIGN VISARGA (Tirh)
	0xC03, // C03 (◌ః) TELUGU SIGN VISARGA
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// C82 (◌ಂ) KANNADA SIGN ANUSVARA (Knda)
	// D02 (◌ം) MALAYALAM SIGN ANUSVARA (Mlym)
	// D82 (◌ං) SINHALA SIGN ANUSVARAYA (Sinh)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// A66 (੦) GURMUKHI DIGIT ZERO (Guru)
	// AE6 (૦) GUJARATI DIGIT ZERO (Gujr)
	// BE6 (௦) TAMIL DIGIT ZERO (Taml)
	// CE6 (೦) KANNADA DIGIT ZERO (Knda)
	// D66 (൦) MALAYALAM DIGIT ZERO (Mlym)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// ED0 (໐) LAO DIGIT ZERO (Laoo)
	// 1040 (၀) MYANMAR DIGIT ZERO (Mymr)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 2C9F (ⲟ) COPTIC SMALL LETTER O (Copt)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 10FF (ჿ) GEORGIAN LETTER LABIAL SIGN (Geor)
	// 585 (օ) ARMENIAN SMALL LETTER OH (Armn)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	// D20 (ഠ) MALAYALAM LETTER TTHA (Mlym)
	// 101D (ဝ) MYANMAR LETTER WA (Mymr)
	// 104EA (𐓪) OSAGE SMALL LETTER O (Osge)
	// 118C8 (𑣈) WARANG CITI SMALL LETTER E (Wara)
	// 118D7 (𑣗) WARANG CITI SMALL LETTER BU (Wara)
	// 1042C (𐐬) DESERET SMALL LETTER LONG O (Dsrt)
	0xC02, // C02 (◌ం) TELUGU SIGN ANUSVARA
	0xC66, // C66 (౦) TELUGU DIGIT ZERO
	// "ఒౌ"
	// C94 (ಔ) KANNADA LETTER AU (Knda)
	0xC14, // C14 (ఔ) TELUGU LETTER AU
	// "ఒౕ"
	// C93 (ಓ) KANNADA LETTER OO (Knda)
	0xC13, // C13 (ఓ) TELUGU LETTER OO
	// "ధּ"
	// C27 (ధ) TELUGU LETTER DHA + 5BC (◌ּ) HEBREW POINT DAGESH OR MAPIQ (Telu,Hebr)
	0xC25, // C25 (థ) TELUGU LETTER THA
	// "రּ"
	// C30 (ర) TELUGU LETTER RA + 5BC (◌ּ) HEBREW POINT DAGESH OR MAPIQ (Telu,Hebr)
	0xC20, // C20 (ఠ) TELUGU LETTER TTHA
]