// created: 2022-10-24T08:40:32.896Z
// version: 15.0.0
export default [
	
	// "-"
	// allowed since restricted and hyphen isn't allowed
	0x5BE, // (־) HEBREW PUNCTUATION MAQAF
	
	// "́"
	// 618 (◌ؘ) ARABIC SMALL FATHA (Arab)
	// 64E (◌َ) ARABIC FATHA (Arab)
	//0x59C, // 59C (◌֜) HEBREW ACCENT GERESH
	//0x59D, // 59D (◌֝) HEBREW ACCENT GERESH MUQDAM
	// "̊"
	// 6DF (◌۟) ARABIC SMALL HIGH ROUNDED ZERO (Arab)
	// 652 (◌ْ) ARABIC SUKUN (Arab)
	// E4D (◌ํ) THAI CHARACTER NIKHAHIT (Thai)
	//0x5AF, // 5AF (◌֯) HEBREW MARK MASORA CIRCLE
	// "̇"
	// 6EC (◌۬) ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE (Arab)
	// 8EA (◌࣪) ARABIC TONE ONE DOT ABOVE (Arab)
	// 902 (◌ं) DEVANAGARI SIGN ANUSVARA (Deva)
	//0x5C4, // 5C4 (◌ׄ) HEBREW MARK UPPER DOT
	//0x5B9, // 5B9 (◌ֹ) HEBREW POINT HOLAM
	//0x5BA, // 5BA (◌ֺ) HEBREW POINT HOLAM HASER FOR VAV
	//0x5C2, // 5C2 (◌ׂ) HEBREW POINT SIN DOT
	//0x5C1, // 5C1 (◌ׁ) HEBREW POINT SHIN DOT
	// "̣"
	// 8ED (◌࣭) ARABIC TONE ONE DOT BELOW (Arab)
	// 65C (◌ٜ) ARABIC VOWEL SIGN DOT BELOW (Arab)
	// 93C (◌़) DEVANAGARI SIGN NUKTA (Deva)
	//0x5B4, // 5B4 (◌ִ) HEBREW POINT HIRIQ
	// "l"
	// 6C (l) LATIN SMALL LETTER L (Latn)
	// 661 (١) ARABIC-INDIC DIGIT ONE (Arab)
	// 627 (ا) ARABIC LETTER ALEF (Arab)
	0x5D5, // 5D5 (ו) HEBREW LETTER VAV
	0x5DF, // 5DF (ן) HEBREW LETTER FINAL NUN
	// "ll"
	// 6C (l) LATIN SMALL LETTER L + 6C (l) LATIN SMALL LETTER L (Latn)
	0x5F0, // 5F0 (װ) HEBREW LIGATURE YIDDISH DOUBLE VAV
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	0x5E1, // 5E1 (ס) HEBREW LETTER SAMEKH
	// "v"
	// 76 (v) LATIN SMALL LETTER V (Latn)
	// 3BD (ν) GREEK SMALL LETTER NU (Grek)
	0x5D8, // 5D8 (ט) HEBREW LETTER TET
]