// created: 2022-10-24T08:28:53.160Z
// version: 15.0.0
export default [
	// "☧"
	// 2627 (☧) CHI RHO (Zyyy)
	0x2CE9, // 2CE9 (⳩) COPTIC SYMBOL KHI RO
	// "c"
	// 63 (c) LATIN SMALL LETTER C (Latn)
	// 441 (с) CYRILLIC SMALL LETTER ES (Cyrl)
	// 1043D (𐐽) DESERET SMALL LETTER CHEE (Dsrt)
	0x2CA5, // 2CA5 (ⲥ) COPTIC SMALL LETTER SIMA
	// "ꞓ"
	// 3B5 (ε) GREEK SMALL LETTER EPSILON (Grek)
	// 454 (є) CYRILLIC SMALL LETTER UKRAINIAN IE (Cyrl)
	// 511 (ԑ) CYRILLIC SMALL LETTER REVERSED ZE (Cyrl)
	// 118CE (𑣎) WARANG CITI SMALL LETTER YUJ (Wara)
	// 10429 (𐐩) DESERET SMALL LETTER LONG E (Dsrt)
	0x2C89, // 2C89 (ⲉ) COPTIC SMALL LETTER EIE
	// "ʟ"
	// 10443 (𐑃) DESERET SMALL LETTER ETH (Dsrt)
	0x2CD1, // 2CD1 (ⳑ) COPTIC SMALL LETTER L-SHAPED HA
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// C02 (◌ం) TELUGU SIGN ANUSVARA (Telu)
	// C82 (◌ಂ) KANNADA SIGN ANUSVARA (Knda)
	// D02 (◌ം) MALAYALAM SIGN ANUSVARA (Mlym)
	// D82 (◌ං) SINHALA SIGN ANUSVARAYA (Sinh)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// A66 (੦) GURMUKHI DIGIT ZERO (Guru)
	// AE6 (૦) GUJARATI DIGIT ZERO (Gujr)
	// BE6 (௦) TAMIL DIGIT ZERO (Taml)
	// C66 (౦) TELUGU DIGIT ZERO (Telu)
	// CE6 (೦) KANNADA DIGIT ZERO (Knda)
	// D66 (൦) MALAYALAM DIGIT ZERO (Mlym)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// ED0 (໐) LAO DIGIT ZERO (Laoo)
	// 1040 (၀) MYANMAR DIGIT ZERO (Mymr)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 10FF (ჿ) GEORGIAN LETTER LABIAL SIGN (Geor)
	// 585 (օ) ARMENIAN SMALL LETTER OH (Armn)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	// D20 (ഠ) MALAYALAM LETTER TTHA (Mlym)
	// 101D (ဝ) MYANMAR LETTER WA (Mymr)
	// 104EA (𐓪) OSAGE SMALL LETTER O (Osge)
	// 118C8 (𑣈) WARANG CITI SMALL LETTER E (Wara)
	// 118D7 (𑣗) WARANG CITI SMALL LETTER BU (Wara)
	// 1042C (𐐬) DESERET SMALL LETTER LONG O (Dsrt)
	0x2C9F, // 2C9F (ⲟ) COPTIC SMALL LETTER O
	// "p"
	// 70 (p) LATIN SMALL LETTER P (Latn)
	// 3C1 (ρ) GREEK SMALL LETTER RHO (Grek)
	// 440 (р) CYRILLIC SMALL LETTER ER (Cyrl)
	0x2CA3, // 2CA3 (ⲣ) COPTIC SMALL LETTER RO
	// "ɸ"
	// 3C6 (φ) GREEK SMALL LETTER PHI (Grek)
	// 444 (ф) CYRILLIC SMALL LETTER EF (Cyrl)
	0x2CAB, // 2CAB (ⲫ) COPTIC SMALL LETTER FI
	// "ĸ"
	// 3BA (κ) GREEK SMALL LETTER KAPPA (Grek)
	// 43A (к) CYRILLIC SMALL LETTER KA (Cyrl)
	0x2C95, // 2C95 (ⲕ) COPTIC SMALL LETTER KAPA
	// "r"
	// 72 (r) LATIN SMALL LETTER R (Latn)
	// 433 (г) CYRILLIC SMALL LETTER GHE (Cyrl)
	0x2C85, // 2C85 (ⲅ) COPTIC SMALL LETTER GAMMA
	// "ȝ"
	// 4E1 (ӡ) CYRILLIC SMALL LETTER ABKHASIAN DZE (Cyrl)
	0x2CCD, // 2CCD (ⳍ) COPTIC SMALL LETTER OLD COPTIC HORI
	// "χ"
	// 3C7 (χ) GREEK SMALL LETTER CHI (Grek)
	0x2CAD, // 2CAD (ⲭ) COPTIC SMALL LETTER KHI
	// "ω"
	// 3C9 (ω) GREEK SMALL LETTER OMEGA (Grek)
	0x2CB1, // 2CB1 (ⲱ) COPTIC SMALL LETTER OOU
	// "ш"
	// 448 (ш) CYRILLIC SMALL LETTER SHA (Cyrl)
	0x2CBD, // 2CBD (ⲽ) COPTIC SMALL LETTER CRYPTOGRAMMIC NI
]