export default [
	// computed: 2022-10-15T05:22:41.098Z
	// version: 15.0.0
	// "a"
	// 61 (a) LATIN SMALL LETTER A (Latn)
	// 3B1 (α) GREEK SMALL LETTER ALPHA (Grek)
	0x430, // 430 (а) CYRILLIC SMALL LETTER A
	// "ae"
	// 61 (a) LATIN SMALL LETTER A + 65 (e) LATIN SMALL LETTER E (Latn)
	// E6 (æ) LATIN SMALL LETTER AE (Latn)
	0x4D5, // 4D5 (ӕ) CYRILLIC SMALL LIGATURE A IE
	// "c"
	// 63 (c) LATIN SMALL LETTER C (Latn)
	0x441, // 441 (с) CYRILLIC SMALL LETTER ES
	// "c̦"
	// E7 (ç) LATIN SMALL LETTER C WITH CEDILLA (Latn)
	0x4AB, // 4AB (ҫ) CYRILLIC SMALL LETTER ES WITH DESCENDER
	// "ꞓ"
	// 3B5 (ε) GREEK SMALL LETTER EPSILON (Grek)
	0x454, // 454 (є) CYRILLIC SMALL LETTER UKRAINIAN IE
	0x511, // 511 (ԑ) CYRILLIC SMALL LETTER REVERSED ZE
	// "d"
	// 64 (d) LATIN SMALL LETTER D (Latn)
	0x501, // 501 (ԁ) CYRILLIC SMALL LETTER KOMI DE
	// "e"
	// 65 (e) LATIN SMALL LETTER E (Latn)
	0x435, // 435 (е) CYRILLIC SMALL LETTER IE
	0x4BD, // 4BD (ҽ) CYRILLIC SMALL LETTER ABKHASIAN CHE
	// "h"
	// 68 (h) LATIN SMALL LETTER H (Latn)
	0x4BB, // 4BB (һ) CYRILLIC SMALL LETTER SHHA
	// "i"
	// 69 (i) LATIN SMALL LETTER I (Latn)
	// 3B9 (ι) GREEK SMALL LETTER IOTA (Grek)
	0x456, // 456 (і) CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
	0xA647, // A647 (ꙇ) CYRILLIC SMALL LETTER IOTA
	0x4CF, // 4CF (ӏ) CYRILLIC SMALL LETTER PALOCHKA
	// "j"
	// 6A (j) LATIN SMALL LETTER J (Latn)
	// 3F3 (ϳ) GREEK LETTER YOT (Grek)
	0x458, // 458 (ј) CYRILLIC SMALL LETTER JE
	// "ᴎ"
	// 377 (ͷ) GREEK SMALL LETTER PAMPHYLIAN DIGAMMA (Grek)
	0x438, // 438 (и) CYRILLIC SMALL LETTER I
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	0x43E, // 43E (о) CYRILLIC SMALL LETTER O
	// "oo"
	// 6F (o) LATIN SMALL LETTER O + 6F (o) LATIN SMALL LETTER O (Latn)
	0xA699, // A699 (ꚙ) CYRILLIC SMALL LETTER DOUBLE O
	// "p"
	// 70 (p) LATIN SMALL LETTER P (Latn)
	// 3C1 (ρ) GREEK SMALL LETTER RHO (Grek)
	0x440, // 440 (р) CYRILLIC SMALL LETTER ER
	// "ɸ"
	// 3C6 (φ) GREEK SMALL LETTER PHI (Grek)
	0x444, // 444 (ф) CYRILLIC SMALL LETTER EF
	// "q"
	// 71 (q) LATIN SMALL LETTER Q (Latn)
	0x51B, // 51B (ԛ) CYRILLIC SMALL LETTER QA
	// "ĸ"
	// 3BA (κ) GREEK SMALL LETTER KAPPA (Grek)
	0x43A, // 43A (к) CYRILLIC SMALL LETTER KA
	// "r"
	// 72 (r) LATIN SMALL LETTER R (Latn)
	// 1D26 (ᴦ) GREEK LETTER SMALL CAPITAL GAMMA (Grek)
	0x433, // 433 (г) CYRILLIC SMALL LETTER GHE
	// "s"
	// 73 (s) LATIN SMALL LETTER S (Latn)
	0x455, // 455 (ѕ) CYRILLIC SMALL LETTER DZE
	// "ᴛ"
	// 3C4 (τ) GREEK SMALL LETTER TAU (Grek)
	0x442, // 442 (т) CYRILLIC SMALL LETTER TE
	// "v"
	// 76 (v) LATIN SMALL LETTER V (Latn)
	// 3BD (ν) GREEK SMALL LETTER NU (Grek)
	0x475, // 475 (ѵ) CYRILLIC SMALL LETTER IZHITSA
	// "w"
	// 77 (w) LATIN SMALL LETTER W (Latn)
	0x461, // 461 (ѡ) CYRILLIC SMALL LETTER OMEGA
	0x51D, // 51D (ԝ) CYRILLIC SMALL LETTER WE
	// "x"
	// 78 (x) LATIN SMALL LETTER X (Latn)
	0x445, // 445 (х) CYRILLIC SMALL LETTER HA
	// "y"
	// 79 (y) LATIN SMALL LETTER Y (Latn)
	// 3B3 (γ) GREEK SMALL LETTER GAMMA (Grek)
	0x443, // 443 (у) CYRILLIC SMALL LETTER U
	0x4AF, // 4AF (ү) CYRILLIC SMALL LETTER STRAIGHT U
	// "π"
	// 1D28 (ᴨ) GREEK LETTER SMALL CAPITAL PI (Grek)
	0x43F, // 43F (п) CYRILLIC SMALL LETTER PE
	// "ψ"
	// 3C8 (ψ) GREEK SMALL LETTER PSI (Grek)
	0x471, // 471 (ѱ) CYRILLIC SMALL LETTER PSI
	// "ω"
	// 3C9 (ω) GREEK SMALL LETTER OMEGA (Grek)
	0xA64D, // A64D (ꙍ) CYRILLIC SMALL LETTER BROAD OMEGA
]