// created: 2022-10-24T08:28:55.093Z
// version: 15.0.0
export default [
	// "3"
	// 33 (3) DIGIT THREE (Zyyy)
	// 16F3B (𖼻) MIAO LETTER ZA (Plrd)
	0x118CA, // 118CA (𑣊) WARANG CITI SMALL LETTER ANG
	// "6"
	// 36 (6) DIGIT SIX (Zyyy)
	// 431 (б) CYRILLIC SMALL LETTER BE (Cyrl)
	// 13EE (Ꮾ) CHEROKEE LETTER WV (Cher)
	0x118D5, // 118D5 (𑣕) WARANG CITI SMALL LETTER AT
	// "7"
	// 37 (7) DIGIT SEVEN (Zyyy)
	0x118C6, // 118C6 (𑣆) WARANG CITI SMALL LETTER II
	// "9"
	// 39 (9) DIGIT NINE (Zyyy)
	// A67 (੧) GURMUKHI DIGIT ONE (Guru)
	// B68 (୨) ORIYA DIGIT TWO (Orya)
	// 9ED (৭) BENGALI DIGIT SEVEN (Beng)
	// D6D (൭) MALAYALAM DIGIT SEVEN (Mlym)
	0x118CC, // 118CC (𑣌) WARANG CITI SMALL LETTER KO
	0x118D6, // 118D6 (𑣖) WARANG CITI SMALL LETTER AM
	// "٩"
	// 669 (٩) ARABIC-INDIC DIGIT NINE (Arab)
	// 967 (१) DEVANAGARI DIGIT ONE (Deva)
	0x118E4, // 118E4 (𑣤) WARANG CITI DIGIT FOUR
	// "C"
	// 13DF (Ꮯ) CHEROKEE LETTER TLI (Cher)
	// A4DA (ꓚ) LISU LETTER CA (Lisu)
	// 102A2 (𐊢) CARIAN LETTER D (Cari)
	// 10302 (𐌂) OLD ITALIC LETTER KE (Ital)
	// 1051C (𐔜) ELBASAN LETTER SHE (Elba)
	0x118F2, // 118F2 (𑣲) WARANG CITI NUMBER NINETY
	0x118E9, // 118E9 (𑣩) WARANG CITI DIGIT NINE
	// "ꞓ"
	// 3B5 (ε) GREEK SMALL LETTER EPSILON (Grek)
	// 2C89 (ⲉ) COPTIC SMALL LETTER EIE (Copt)
	// 454 (є) CYRILLIC SMALL LETTER UKRAINIAN IE (Cyrl)
	// 511 (ԑ) CYRILLIC SMALL LETTER REVERSED ZE (Cyrl)
	// 10429 (𐐩) DESERET SMALL LETTER LONG E (Dsrt)
	0x118CE, // 118CE (𑣎) WARANG CITI SMALL LETTER YUJ
	// "F"
	// 15B4 (ᖴ) CANADIAN SYLLABICS BLACKFOOT WE (Cans)
	// A4DD (ꓝ) LISU LETTER TSA (Lisu)
	// 10287 (𐊇) LYCIAN LETTER W (Lyci)
	// 102A5 (𐊥) CARIAN LETTER R (Cari)
	// 10525 (𐔥) ELBASAN LETTER GHE (Elba)
	0x118C2, // 118C2 (𑣂) WARANG CITI SMALL LETTER WI
	// "i"
	// 69 (i) LATIN SMALL LETTER I (Latn)
	// 3B9 (ι) GREEK SMALL LETTER IOTA (Grek)
	// 456 (і) CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I (Cyrl)
	// 4CF (ӏ) CYRILLIC SMALL LETTER PALOCHKA (Cyrl)
	// 13A5 (Ꭵ) CHEROKEE LETTER V (Cher)
	0x118C3, // 118C3 (𑣃) WARANG CITI SMALL LETTER YU
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// C02 (◌ం) TELUGU SIGN ANUSVARA (Telu)
	// C82 (◌ಂ) KANNADA SIGN ANUSVARA (Knda)
	// D02 (◌ം) MALAYALAM SIGN ANUSVARA (Mlym)
	// D82 (◌ං) SINHALA SIGN ANUSVARAYA (Sinh)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// A66 (੦) GURMUKHI DIGIT ZERO (Guru)
	// AE6 (૦) GUJARATI DIGIT ZERO (Gujr)
	// BE6 (௦) TAMIL DIGIT ZERO (Taml)
	// C66 (౦) TELUGU DIGIT ZERO (Telu)
	// CE6 (೦) KANNADA DIGIT ZERO (Knda)
	// D66 (൦) MALAYALAM DIGIT ZERO (Mlym)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// ED0 (໐) LAO DIGIT ZERO (Laoo)
	// 1040 (၀) MYANMAR DIGIT ZERO (Mymr)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 2C9F (ⲟ) COPTIC SMALL LETTER O (Copt)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 10FF (ჿ) GEORGIAN LETTER LABIAL SIGN (Geor)
	// 585 (օ) ARMENIAN SMALL LETTER OH (Armn)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	// D20 (ഠ) MALAYALAM LETTER TTHA (Mlym)
	// 101D (ဝ) MYANMAR LETTER WA (Mymr)
	// 104EA (𐓪) OSAGE SMALL LETTER O (Osge)
	// 1042C (𐐬) DESERET SMALL LETTER LONG O (Dsrt)
	0x118C8, // 118C8 (𑣈) WARANG CITI SMALL LETTER E
	0x118D7, // 118D7 (𑣗) WARANG CITI SMALL LETTER BU
	// "O"
	// 30 (0) DIGIT ZERO (Zyyy)
	// 7C0 (߀) NKO DIGIT ZERO (Nkoo)
	// 9E6 (০) BENGALI DIGIT ZERO (Beng)
	// B66 (୦) ORIYA DIGIT ZERO (Orya)
	// 3007 (〇) IDEOGRAPHIC NUMBER ZERO (Hani)
	// 114D0 (𑓐) TIRHUTA DIGIT ZERO (Tirh)
	// 2D54 (ⵔ) TIFINAGH LETTER YAR (Tfng)
	// 12D0 (ዐ) ETHIOPIC SYLLABLE PHARYNGEAL A (Ethi)
	// B20 (ଠ) ORIYA LETTER TTHA (Orya)
	// A4F3 (ꓳ) LISU LETTER O (Lisu)
	// 10292 (𐊒) LYCIAN LETTER U (Lyci)
	// 102AB (𐊫) CARIAN LETTER O (Cari)
	// 10516 (𐔖) ELBASAN LETTER O (Elba)
	0x118E0, // 118E0 (𑣠) WARANG CITI DIGIT ZERO
	// "rn"
	// 72 (r) LATIN SMALL LETTER R + 6E (n) LATIN SMALL LETTER N (Latn)
	// 6D (m) LATIN SMALL LETTER M (Latn)
	// 11700 (𑜀) AHOM LETTER KA (Ahom)
	0x118E3, // 118E3 (𑣣) WARANG CITI DIGIT THREE
	// "s"
	// 73 (s) LATIN SMALL LETTER S (Latn)
	// 455 (ѕ) CYRILLIC SMALL LETTER DZE (Cyrl)
	// 10448 (𐑈) DESERET SMALL LETTER ZHEE (Dsrt)
	0x118C1, // 118C1 (𑣁) WARANG CITI SMALL LETTER A
	// "u"
	// 75 (u) LATIN SMALL LETTER U (Latn)
	// 3C5 (υ) GREEK SMALL LETTER UPSILON (Grek)
	// 57D (ս) ARMENIAN SMALL LETTER SEH (Armn)
	// 104F6 (𐓶) OSAGE SMALL LETTER U (Osge)
	0x118D8, // 118D8 (𑣘) WARANG CITI SMALL LETTER PU
	// "v"
	// 76 (v) LATIN SMALL LETTER V (Latn)
	// 3BD (ν) GREEK SMALL LETTER NU (Grek)
	// 5D8 (ט) HEBREW LETTER TET (Hebr)
	// 11706 (𑜆) AHOM LETTER PA (Ahom)
	0x118C0, // 118C0 (𑣀) WARANG CITI SMALL LETTER NGAA
	// "W"
	// 13B3 (Ꮃ) CHEROKEE LETTER LA (Cher)
	// 13D4 (Ꮤ) CHEROKEE LETTER TA (Cher)
	// A4EA (ꓪ) LISU LETTER WA (Lisu)
	0x118EF, // 118EF (𑣯) WARANG CITI NUMBER SIXTY
	0x118E6, // 118E6 (𑣦) WARANG CITI DIGIT SIX
	// "X"
	// 166D (᙭) CANADIAN SYLLABICS CHI SIGN (Cans)
	// 10322 (𐌢) OLD ITALIC NUMERAL TEN (Ital)
	// 2D5D (ⵝ) TIFINAGH LETTER YATH (Tfng)
	// 16B7 (ᚷ) RUNIC LETTER GEBO GYFU G (Runr)
	// A4EB (ꓫ) LISU LETTER SHA (Lisu)
	// 10290 (𐊐) LYCIAN LETTER MM (Lyci)
	// 102B4 (𐊴) CARIAN LETTER X (Cari)
	// 10317 (𐌗) OLD ITALIC LETTER EKS (Ital)
	// 10527 (𐔧) ELBASAN LETTER KHE (Elba)
	0x118EC, // 118EC (𑣬) WARANG CITI NUMBER THIRTY
	// "y"
	// 79 (y) LATIN SMALL LETTER Y (Latn)
	// 3B3 (γ) GREEK SMALL LETTER GAMMA (Grek)
	// 443 (у) CYRILLIC SMALL LETTER U (Cyrl)
	// 4AF (ү) CYRILLIC SMALL LETTER STRAIGHT U (Cyrl)
	// 10E7 (ყ) GEORGIAN LETTER QAR (Geor)
	0x118DC, // 118DC (𑣜) WARANG CITI SMALL LETTER HAR
	// "z"
	// 7A (z) LATIN SMALL LETTER Z (Latn)
	0x118C4, // 118C4 (𑣄) WARANG CITI SMALL LETTER YA
	// "Z"
	// 13C3 (Ꮓ) CHEROKEE LETTER NO (Cher)
	// A4DC (ꓜ) LISU LETTER DZA (Lisu)
	0x118E5, // 118E5 (𑣥) WARANG CITI DIGIT FIVE
]