// created: 2022-10-24T08:40:32.911Z
// version: 15.0.0
export default [
	// "̊"
	// 5AF (◌֯) HEBREW MARK MASORA CIRCLE (Hebr)
	// 6DF (◌۟) ARABIC SMALL HIGH ROUNDED ZERO (Arab)
	// 652 (◌ْ) ARABIC SUKUN (Arab)
	//0xE4D, // E4D (◌ํ) THAI CHARACTER NIKHAHIT
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	0xE50, // E50 (๐) THAI DIGIT ZERO
]