export default [
	// computed: 2022-09-25T06:29:13.521Z
	// version: 15.0.0
	0xA644, // A644 (Ꙅ) CYRILLIC CAPITAL LETTER REVERSED DZE == 32 (2) DIGIT TWO
	0x417, // 417 (З) CYRILLIC CAPITAL LETTER ZE == 33 (3) DIGIT THREE
	0x4E0, // 4E0 (Ӡ) CYRILLIC CAPITAL LETTER ABKHASIAN DZE == 33 (3) DIGIT THREE
	0x431, // 431 (б) CYRILLIC SMALL LETTER BE == 36 (6) DIGIT SIX
	0xA67C, // A67C (x꙼) COMBINING CYRILLIC KAVYKA == 306 (x̆) COMBINING BREVE
	0x2DEA, // 2DEA (xⷪ) COMBINING CYRILLIC LETTER O == 30A (x̊) COMBINING RING ABOVE
	0xA66F, // A66F (x꙯) COMBINING CYRILLIC VZMET == 20E9 (x⃩) COMBINING WIDE BRIDGE ABOVE
	0xA67E, // A67E (꙾) CYRILLIC KAVYKA == 2C7 (ˇ) CARON
	0x44A, // 44A (ъ) CYRILLIC SMALL LETTER HARD SIGN == ˉb [2C9 (ˉ) MODIFIER LETTER MACRON,62 (b) LATIN SMALL LETTER B]
	0xA651, // A651 (ꙑ) CYRILLIC SMALL LETTER YERU WITH BACK YER == ˉbi [2C9 (ˉ) MODIFIER LETTER MACRON,62 (b) LATIN SMALL LETTER B,69 (i) LATIN SMALL LETTER I]
	0x498, // 498 (Ҙ) CYRILLIC CAPITAL LETTER ZE WITH DESCENDER == 3̦ [33 (3) DIGIT THREE,326 (x̦) COMBINING COMMA BELOW]
	0x430, // 430 (а) CYRILLIC SMALL LETTER A == 61 (a) LATIN SMALL LETTER A
	0x2DF6, // 2DF6 (xⷶ) COMBINING CYRILLIC LETTER A == 363 (xͣ) COMBINING LATIN SMALL LETTER A
	0x410, // 410 (А) CYRILLIC CAPITAL LETTER A == 41 (A) LATIN CAPITAL LETTER A
	0x4D5, // 4D5 (ӕ) CYRILLIC SMALL LIGATURE A IE == ae [61 (a) LATIN SMALL LETTER A,65 (e) LATIN SMALL LETTER E]
	0x4D4, // 4D4 (Ӕ) CYRILLIC CAPITAL LIGATURE A IE == AE [41 (A) LATIN CAPITAL LETTER A,45 (E) LATIN CAPITAL LETTER E]
	0x42C, // 42C (Ь) CYRILLIC CAPITAL LETTER SOFT SIGN == 62 (b) LATIN SMALL LETTER B
	0x412, // 412 (В) CYRILLIC CAPITAL LETTER VE == 42 (B) LATIN CAPITAL LETTER B
	0x411, // 411 (Б) CYRILLIC CAPITAL LETTER BE == b̄ [62 (b) LATIN SMALL LETTER B,304 (x̄) COMBINING MACRON]
	0x48D, // 48D (ҍ) CYRILLIC SMALL LETTER SEMISOFT SIGN == b̵ [62 (b) LATIN SMALL LETTER B,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x48C, // 48C (Ҍ) CYRILLIC CAPITAL LETTER SEMISOFT SIGN == b̵ [62 (b) LATIN SMALL LETTER B,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x463, // 463 (ѣ) CYRILLIC SMALL LETTER YAT == b̵ [62 (b) LATIN SMALL LETTER B,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x462, // 462 (Ѣ) CYRILLIC CAPITAL LETTER YAT == b̵ [62 (b) LATIN SMALL LETTER B,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x42B, // 42B (Ы) CYRILLIC CAPITAL LETTER YERU == bl [62 (b) LATIN SMALL LETTER B,6C (l) LATIN SMALL LETTER L]
	0x432, // 432 (в) CYRILLIC SMALL LETTER VE == 299 (ʙ) LATIN LETTER SMALL CAPITAL B
	0x441, // 441 (с) CYRILLIC SMALL LETTER ES == 63 (c) LATIN SMALL LETTER C
	0x2DED, // 2DED (xⷭ) COMBINING CYRILLIC LETTER ES == 368 (xͨ) COMBINING LATIN SMALL LETTER C
	0x421, // 421 (С) CYRILLIC CAPITAL LETTER ES == 43 (C) LATIN CAPITAL LETTER C
	0x4AB, // 4AB (ҫ) CYRILLIC SMALL LETTER ES WITH DESCENDER == c̦ [63 (c) LATIN SMALL LETTER C,326 (x̦) COMBINING COMMA BELOW]
	0x4AA, // 4AA (Ҫ) CYRILLIC CAPITAL LETTER ES WITH DESCENDER == C̦ [43 (C) LATIN CAPITAL LETTER C,326 (x̦) COMBINING COMMA BELOW]
	0x454, // 454 (є) CYRILLIC SMALL LETTER UKRAINIAN IE == A793 (ꞓ) LATIN SMALL LETTER C WITH BAR
	0x511, // 511 (ԑ) CYRILLIC SMALL LETTER REVERSED ZE == A793 (ꞓ) LATIN SMALL LETTER C WITH BAR
	0x404, // 404 (Є) CYRILLIC CAPITAL LETTER UKRAINIAN IE == A792 (Ꞓ) LATIN CAPITAL LETTER C WITH BAR
	0x501, // 501 (ԁ) CYRILLIC SMALL LETTER KOMI DE == 64 (d) LATIN SMALL LETTER D
	0x435, // 435 (е) CYRILLIC SMALL LETTER IE == 65 (e) LATIN SMALL LETTER E
	0x4BD, // 4BD (ҽ) CYRILLIC SMALL LETTER ABKHASIAN CHE == 65 (e) LATIN SMALL LETTER E
	0x2DF7, // 2DF7 (xⷷ) COMBINING CYRILLIC LETTER IE == 364 (xͤ) COMBINING LATIN SMALL LETTER E
	0x415, // 415 (Е) CYRILLIC CAPITAL LETTER IE == 45 (E) LATIN CAPITAL LETTER E
	0x4BF, // 4BF (ҿ) CYRILLIC SMALL LETTER ABKHASIAN CHE WITH DESCENDER == ę [65 (e) LATIN SMALL LETTER E,328 (x̨) COMBINING OGONEK]
	0x4D9, // 4D9 (ә) CYRILLIC SMALL LETTER SCHWA == 1DD (ǝ) LATIN SMALL LETTER TURNED E
	0x4D8, // 4D8 (Ә) CYRILLIC CAPITAL LETTER SCHWA == 18F (Ə) LATIN CAPITAL LETTER SCHWA
	0x510, // 510 (Ԑ) CYRILLIC CAPITAL LETTER REVERSED ZE == 190 (Ɛ) LATIN CAPITAL LETTER OPEN E
	0x437, // 437 (з) CYRILLIC SMALL LETTER ZE == 25C (ɜ) LATIN SMALL LETTER REVERSED OPEN E
	0x499, // 499 (ҙ) CYRILLIC SMALL LETTER ZE WITH DESCENDER == ɜ̦ [25C (ɜ) LATIN SMALL LETTER REVERSED OPEN E,326 (x̦) COMBINING COMMA BELOW]
	0x50C, // 50C (Ԍ) CYRILLIC CAPITAL LETTER KOMI SJE == 47 (G) LATIN CAPITAL LETTER G
	0x50D, // 50D (ԍ) CYRILLIC SMALL LETTER KOMI SJE == 262 (ɢ) LATIN LETTER SMALL CAPITAL G
	0x4BB, // 4BB (һ) CYRILLIC SMALL LETTER SHHA == 68 (h) LATIN SMALL LETTER H
	0x41D, // 41D (Н) CYRILLIC CAPITAL LETTER EN == 48 (H) LATIN CAPITAL LETTER H
	0x1D78, // 1D78 (ᵸ) MODIFIER LETTER CYRILLIC EN == 1D34 (ᴴ) MODIFIER LETTER CAPITAL H
	0xA695, // A695 (ꚕ) CYRILLIC SMALL LETTER HWE == h̔ [68 (h) LATIN SMALL LETTER H,314 (x̔) COMBINING REVERSED COMMA ABOVE]
	0x4A2, // 4A2 (Ң) CYRILLIC CAPITAL LETTER EN WITH DESCENDER == H̩ [48 (H) LATIN CAPITAL LETTER H,329 (x̩) COMBINING VERTICAL LINE BELOW]
	0x45B, // 45B (ћ) CYRILLIC SMALL LETTER TSHE == h̵ [68 (h) LATIN SMALL LETTER H,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x4C9, // 4C9 (Ӊ) CYRILLIC CAPITAL LETTER EN WITH TAIL == H̦ [48 (H) LATIN CAPITAL LETTER H,326 (x̦) COMBINING COMMA BELOW]
	0x4C7, // 4C7 (Ӈ) CYRILLIC CAPITAL LETTER EN WITH HOOK == H̦ [48 (H) LATIN CAPITAL LETTER H,326 (x̦) COMBINING COMMA BELOW]
	0x43D, // 43D (н) CYRILLIC SMALL LETTER EN == 29C (ʜ) LATIN LETTER SMALL CAPITAL H
	0x4A3, // 4A3 (ң) CYRILLIC SMALL LETTER EN WITH DESCENDER == ʜ̩ [29C (ʜ) LATIN LETTER SMALL CAPITAL H,329 (x̩) COMBINING VERTICAL LINE BELOW]
	0x4CA, // 4CA (ӊ) CYRILLIC SMALL LETTER EN WITH TAIL == ʜ̦ [29C (ʜ) LATIN LETTER SMALL CAPITAL H,326 (x̦) COMBINING COMMA BELOW]
	0x4C8, // 4C8 (ӈ) CYRILLIC SMALL LETTER EN WITH HOOK == ʜ̦ [29C (ʜ) LATIN LETTER SMALL CAPITAL H,326 (x̦) COMBINING COMMA BELOW]
	0x50A, // 50A (Ԋ) CYRILLIC CAPITAL LETTER KOMI NJE == 1F6 (Ƕ) LATIN CAPITAL LETTER HWAIR
	0x456, // 456 (і) CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I == 69 (i) LATIN SMALL LETTER I
	0xA647, // A647 (ꙇ) CYRILLIC SMALL LETTER IOTA == 69 (i) LATIN SMALL LETTER I
	0x4CF, // 4CF (ӏ) CYRILLIC SMALL LETTER PALOCHKA == 69 (i) LATIN SMALL LETTER I
	0x458, // 458 (ј) CYRILLIC SMALL LETTER JE == 6A (j) LATIN SMALL LETTER J
	0x408, // 408 (Ј) CYRILLIC CAPITAL LETTER JE == 4A (J) LATIN CAPITAL LETTER J
	0x41A, // 41A (К) CYRILLIC CAPITAL LETTER KA == 4B (K) LATIN CAPITAL LETTER K
	0x49A, // 49A (Қ) CYRILLIC CAPITAL LETTER KA WITH DESCENDER == K̩ [4B (K) LATIN CAPITAL LETTER K,329 (x̩) COMBINING VERTICAL LINE BELOW]
	0x49E, // 49E (Ҟ) CYRILLIC CAPITAL LETTER KA WITH STROKE == K̵ [4B (K) LATIN CAPITAL LETTER K,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x406, // 406 (І) CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I == 6C (l) LATIN SMALL LETTER L
	0x4C0, // 4C0 (Ӏ) CYRILLIC LETTER PALOCHKA == 6C (l) LATIN SMALL LETTER L
	0x42E, // 42E (Ю) CYRILLIC CAPITAL LETTER YU == lO [6C (l) LATIN SMALL LETTER L,4F (O) LATIN CAPITAL LETTER O]
	0x41C, // 41C (М) CYRILLIC CAPITAL LETTER EM == 4D (M) LATIN CAPITAL LETTER M
	0x4CD, // 4CD (Ӎ) CYRILLIC CAPITAL LETTER EM WITH TAIL == M̦ [4D (M) LATIN CAPITAL LETTER M,326 (x̦) COMBINING COMMA BELOW]
	0x2DE8, // 2DE8 (xⷨ) COMBINING CYRILLIC LETTER EM == 1DDF (xᷟ) COMBINING LATIN LETTER SMALL CAPITAL M
	0x438, // 438 (и) CYRILLIC SMALL LETTER I == 1D0E (ᴎ) LATIN LETTER SMALL CAPITAL REVERSED N
	0x43E, // 43E (о) CYRILLIC SMALL LETTER O == 6F (o) LATIN SMALL LETTER O
	0x41E, // 41E (О) CYRILLIC CAPITAL LETTER O == 4F (O) LATIN CAPITAL LETTER O
	0x4E9, // 4E9 (ө) CYRILLIC SMALL LETTER BARRED O == o̵ [6F (o) LATIN SMALL LETTER O,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x473, // 473 (ѳ) CYRILLIC SMALL LETTER FITA == o̵ [6F (o) LATIN SMALL LETTER O,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x4E8, // 4E8 (Ө) CYRILLIC CAPITAL LETTER BARRED O == O̵ [4F (O) LATIN CAPITAL LETTER O,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x472, // 472 (Ѳ) CYRILLIC CAPITAL LETTER FITA == O̵ [4F (O) LATIN CAPITAL LETTER O,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0xA699, // A699 (ꚙ) CYRILLIC SMALL LETTER DOUBLE O == oo [6F (o) LATIN SMALL LETTER O,6F (o) LATIN SMALL LETTER O]
	0xA698, // A698 (Ꚙ) CYRILLIC CAPITAL LETTER DOUBLE O == OO [4F (O) LATIN CAPITAL LETTER O,4F (O) LATIN CAPITAL LETTER O]
	0x440, // 440 (р) CYRILLIC SMALL LETTER ER == 70 (p) LATIN SMALL LETTER P
	0x420, // 420 (Р) CYRILLIC CAPITAL LETTER ER == 50 (P) LATIN CAPITAL LETTER P
	0x444, // 444 (ф) CYRILLIC SMALL LETTER EF == 278 (ɸ) LATIN SMALL LETTER PHI
	0x51B, // 51B (ԛ) CYRILLIC SMALL LETTER QA == 71 (q) LATIN SMALL LETTER Q
	0x43A, // 43A (к) CYRILLIC SMALL LETTER KA == 138 (ĸ) LATIN SMALL LETTER KRA
	0x49B, // 49B (қ) CYRILLIC SMALL LETTER KA WITH DESCENDER == ĸ̩ [138 (ĸ) LATIN SMALL LETTER KRA,329 (x̩) COMBINING VERTICAL LINE BELOW]
	0x49F, // 49F (ҟ) CYRILLIC SMALL LETTER KA WITH STROKE == ĸ̵ [138 (ĸ) LATIN SMALL LETTER KRA,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x433, // 433 (г) CYRILLIC SMALL LETTER GHE == 72 (r) LATIN SMALL LETTER R
	0x493, // 493 (ғ) CYRILLIC SMALL LETTER GHE WITH STROKE == r̵ [72 (r) LATIN SMALL LETTER R,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x491, // 491 (ґ) CYRILLIC SMALL LETTER GHE WITH UPTURN == r' [72 (r) LATIN SMALL LETTER R,27 (') APOSTROPHE]
	0x44F, // 44F (я) CYRILLIC SMALL LETTER YA == 1D19 (ᴙ) LATIN LETTER SMALL CAPITAL REVERSED R
	0x455, // 455 (ѕ) CYRILLIC SMALL LETTER DZE == 73 (s) LATIN SMALL LETTER S
	0x405, // 405 (Ѕ) CYRILLIC CAPITAL LETTER DZE == 53 (S) LATIN CAPITAL LETTER S
	0x422, // 422 (Т) CYRILLIC CAPITAL LETTER TE == 54 (T) LATIN CAPITAL LETTER T
	0x4AC, // 4AC (Ҭ) CYRILLIC CAPITAL LETTER TE WITH DESCENDER == T̩ [54 (T) LATIN CAPITAL LETTER T,329 (x̩) COMBINING VERTICAL LINE BELOW]
	0x442, // 442 (т) CYRILLIC SMALL LETTER TE == 1D1B (ᴛ) LATIN LETTER SMALL CAPITAL T
	0x4AD, // 4AD (ҭ) CYRILLIC SMALL LETTER TE WITH DESCENDER == ᴛ̩ [1D1B (ᴛ) LATIN LETTER SMALL CAPITAL T,329 (x̩) COMBINING VERTICAL LINE BELOW]
	0x475, // 475 (ѵ) CYRILLIC SMALL LETTER IZHITSA == 76 (v) LATIN SMALL LETTER V
	0x474, // 474 (Ѵ) CYRILLIC CAPITAL LETTER IZHITSA == 56 (V) LATIN CAPITAL LETTER V
	0x41B, // 41B (Л) CYRILLIC CAPITAL LETTER EL == 245 (Ʌ) LATIN CAPITAL LETTER TURNED V
	0x4C5, // 4C5 (Ӆ) CYRILLIC CAPITAL LETTER EL WITH TAIL == Ʌ̦ [245 (Ʌ) LATIN CAPITAL LETTER TURNED V,326 (x̦) COMBINING COMMA BELOW]
	0x461, // 461 (ѡ) CYRILLIC SMALL LETTER OMEGA == 77 (w) LATIN SMALL LETTER W
	0x51D, // 51D (ԝ) CYRILLIC SMALL LETTER WE == 77 (w) LATIN SMALL LETTER W
	0x51C, // 51C (Ԝ) CYRILLIC CAPITAL LETTER WE == 57 (W) LATIN CAPITAL LETTER W
	0x47D, // 47D (ѽ) CYRILLIC SMALL LETTER OMEGA WITH TITLO == w҆҇ [77 (w) LATIN SMALL LETTER W,486 (x҆) COMBINING CYRILLIC PSILI PNEUMATA,487 (x҇) COMBINING CYRILLIC POKRYTIE]
	0x43C, // 43C (м) CYRILLIC SMALL LETTER EM == 28D (ʍ) LATIN SMALL LETTER TURNED W
	0x4CE, // 4CE (ӎ) CYRILLIC SMALL LETTER EM WITH TAIL == ʍ̦ [28D (ʍ) LATIN SMALL LETTER TURNED W,326 (x̦) COMBINING COMMA BELOW]
	0x445, // 445 (х) CYRILLIC SMALL LETTER HA == 78 (x) LATIN SMALL LETTER X
	0x2DEF, // 2DEF (xⷯ) COMBINING CYRILLIC LETTER HA == 36F (xͯ) COMBINING LATIN SMALL LETTER X
	0x425, // 425 (Х) CYRILLIC CAPITAL LETTER HA == 58 (X) LATIN CAPITAL LETTER X
	0x4B2, // 4B2 (Ҳ) CYRILLIC CAPITAL LETTER HA WITH DESCENDER == X̩ [58 (X) LATIN CAPITAL LETTER X,329 (x̩) COMBINING VERTICAL LINE BELOW]
	0x443, // 443 (у) CYRILLIC SMALL LETTER U == 79 (y) LATIN SMALL LETTER Y
	0x4AF, // 4AF (ү) CYRILLIC SMALL LETTER STRAIGHT U == 79 (y) LATIN SMALL LETTER Y
	0x423, // 423 (У) CYRILLIC CAPITAL LETTER U == 59 (Y) LATIN CAPITAL LETTER Y
	0x4AE, // 4AE (Ү) CYRILLIC CAPITAL LETTER STRAIGHT U == 59 (Y) LATIN CAPITAL LETTER Y
	0x4B1, // 4B1 (ұ) CYRILLIC SMALL LETTER STRAIGHT U WITH STROKE == y̵ [79 (y) LATIN SMALL LETTER Y,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x4B0, // 4B0 (Ұ) CYRILLIC CAPITAL LETTER STRAIGHT U WITH STROKE == Y̵ [59 (Y) LATIN CAPITAL LETTER Y,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x4E1, // 4E1 (ӡ) CYRILLIC SMALL LETTER ABKHASIAN DZE == 21D (ȝ) LATIN SMALL LETTER YOGH
	0xA645, // A645 (ꙅ) CYRILLIC SMALL LETTER REVERSED DZE == 1A8 (ƨ) LATIN SMALL LETTER TONE TWO
	0x44C, // 44C (ь) CYRILLIC SMALL LETTER SOFT SIGN == 185 (ƅ) LATIN SMALL LETTER TONE SIX
	0x44B, // 44B (ы) CYRILLIC SMALL LETTER YERU == ƅi [185 (ƅ) LATIN SMALL LETTER TONE SIX,69 (i) LATIN SMALL LETTER I]
	0xA668, // A668 (Ꙩ) CYRILLIC CAPITAL LETTER MONOCULAR O == 298 (ʘ) LATIN LETTER BILABIAL CLICK
	0x413, // 413 (Г) CYRILLIC CAPITAL LETTER GHE == 393 (Γ) GREEK CAPITAL LETTER GAMMA
	0x492, // 492 (Ғ) CYRILLIC CAPITAL LETTER GHE WITH STROKE == Γ̵ [393 (Γ) GREEK CAPITAL LETTER GAMMA,335 (x̵) COMBINING SHORT STROKE OVERLAY]
	0x490, // 490 (Ґ) CYRILLIC CAPITAL LETTER GHE WITH UPTURN == Γ' [393 (Γ) GREEK CAPITAL LETTER GAMMA,27 (') APOSTROPHE]
	0x43F, // 43F (п) CYRILLIC SMALL LETTER PE == 3C0 (π) GREEK SMALL LETTER PI
	0x41F, // 41F (П) CYRILLIC CAPITAL LETTER PE == 3A0 (Π) GREEK CAPITAL LETTER PI
	0x424, // 424 (Ф) CYRILLIC CAPITAL LETTER EF == 3A6 (Φ) GREEK CAPITAL LETTER PHI
	0x471, // 471 (ѱ) CYRILLIC SMALL LETTER PSI == 3C8 (ψ) GREEK SMALL LETTER PSI
	0x470, // 470 (Ѱ) CYRILLIC CAPITAL LETTER PSI == 3A8 (Ψ) GREEK CAPITAL LETTER PSI
	0xA64D, // A64D (ꙍ) CYRILLIC SMALL LETTER BROAD OMEGA == 3C9 (ω) GREEK SMALL LETTER OMEGA
	0xA650, // A650 (Ꙑ) CYRILLIC CAPITAL LETTER YERU WITH BACK YER == Ъl [42A (Ъ) CYRILLIC CAPITAL LETTER HARD SIGN,6C (l) LATIN SMALL LETTER L]
	0xA69A, // A69A (Ꚛ) CYRILLIC CAPITAL LETTER CROSSED O == 102A8 (𐊨) CARIAN LETTER Q
]