export default [
	// computed: 2022-10-09T21:48:46.343Z
	// version: 15.0.0
	0x431, // 431 (б) CYRILLIC SMALL LETTER BE == 36 (6) DIGIT SIX
	0xA67C, // A67C (◌꙼) COMBINING CYRILLIC KAVYKA == 306 (◌̆) COMBINING BREVE
	0x2DEA, // 2DEA (◌ⷪ) COMBINING CYRILLIC LETTER O == 30A (◌̊) COMBINING RING ABOVE
	0xA66F, // A66F (◌꙯) COMBINING CYRILLIC VZMET == 20E9 (◌⃩) COMBINING WIDE BRIDGE ABOVE
	0xA67E, // A67E (꙾) CYRILLIC KAVYKA == 2C7 (ˇ) CARON
	0x44A, // 44A (ъ) CYRILLIC SMALL LETTER HARD SIGN == ˉb [2C9 (ˉ) MODIFIER LETTER MACRON,62 (b) LATIN SMALL LETTER B]
	0xA651, // A651 (ꙑ) CYRILLIC SMALL LETTER YERU WITH BACK YER == ˉbi [2C9 (ˉ) MODIFIER LETTER MACRON,62 (b) LATIN SMALL LETTER B,69 (i) LATIN SMALL LETTER I]
	0x430, // 430 (а) CYRILLIC SMALL LETTER A == 61 (a) LATIN SMALL LETTER A
	0x2DF6, // 2DF6 (◌ⷶ) COMBINING CYRILLIC LETTER A == 363 (◌ͣ) COMBINING LATIN SMALL LETTER A
	0x4D5, // 4D5 (ӕ) CYRILLIC SMALL LIGATURE A IE == ae [61 (a) LATIN SMALL LETTER A,65 (e) LATIN SMALL LETTER E]
	0x48D, // 48D (ҍ) CYRILLIC SMALL LETTER SEMISOFT SIGN == b̵ [62 (b) LATIN SMALL LETTER B,335 (◌̵) COMBINING SHORT STROKE OVERLAY]
	0x463, // 463 (ѣ) CYRILLIC SMALL LETTER YAT == b̵ [62 (b) LATIN SMALL LETTER B,335 (◌̵) COMBINING SHORT STROKE OVERLAY]
	0x432, // 432 (в) CYRILLIC SMALL LETTER VE == 299 (ʙ) LATIN LETTER SMALL CAPITAL B
	0x441, // 441 (с) CYRILLIC SMALL LETTER ES == 63 (c) LATIN SMALL LETTER C
	0x2DED, // 2DED (◌ⷭ) COMBINING CYRILLIC LETTER ES == 368 (◌ͨ) COMBINING LATIN SMALL LETTER C
	0x4AB, // 4AB (ҫ) CYRILLIC SMALL LETTER ES WITH DESCENDER == c̦ [63 (c) LATIN SMALL LETTER C,326 (◌̦) COMBINING COMMA BELOW]
	0x454, // 454 (є) CYRILLIC SMALL LETTER UKRAINIAN IE == A793 (ꞓ) LATIN SMALL LETTER C WITH BAR
	0x511, // 511 (ԑ) CYRILLIC SMALL LETTER REVERSED ZE == A793 (ꞓ) LATIN SMALL LETTER C WITH BAR
	0x501, // 501 (ԁ) CYRILLIC SMALL LETTER KOMI DE == 64 (d) LATIN SMALL LETTER D
	0x435, // 435 (е) CYRILLIC SMALL LETTER IE == 65 (e) LATIN SMALL LETTER E
	0x4BD, // 4BD (ҽ) CYRILLIC SMALL LETTER ABKHASIAN CHE == 65 (e) LATIN SMALL LETTER E
	0x2DF7, // 2DF7 (◌ⷷ) COMBINING CYRILLIC LETTER IE == 364 (◌ͤ) COMBINING LATIN SMALL LETTER E
	0x4BF, // 4BF (ҿ) CYRILLIC SMALL LETTER ABKHASIAN CHE WITH DESCENDER == ę [65 (e) LATIN SMALL LETTER E,328 (◌̨) COMBINING OGONEK]
	0x4D9, // 4D9 (ә) CYRILLIC SMALL LETTER SCHWA == 1DD (ǝ) LATIN SMALL LETTER TURNED E
	0x437, // 437 (з) CYRILLIC SMALL LETTER ZE == 25C (ɜ) LATIN SMALL LETTER REVERSED OPEN E
	0x499, // 499 (ҙ) CYRILLIC SMALL LETTER ZE WITH DESCENDER == ɜ̦ [25C (ɜ) LATIN SMALL LETTER REVERSED OPEN E,326 (◌̦) COMBINING COMMA BELOW]
	0x50D, // 50D (ԍ) CYRILLIC SMALL LETTER KOMI SJE == 262 (ɢ) LATIN LETTER SMALL CAPITAL G
	0x4BB, // 4BB (һ) CYRILLIC SMALL LETTER SHHA == 68 (h) LATIN SMALL LETTER H
	0xA695, // A695 (ꚕ) CYRILLIC SMALL LETTER HWE == h̔ [68 (h) LATIN SMALL LETTER H,314 (◌̔) COMBINING REVERSED COMMA ABOVE]
	0x45B, // 45B (ћ) CYRILLIC SMALL LETTER TSHE == h̵ [68 (h) LATIN SMALL LETTER H,335 (◌̵) COMBINING SHORT STROKE OVERLAY]
	0x43D, // 43D (н) CYRILLIC SMALL LETTER EN == 29C (ʜ) LATIN LETTER SMALL CAPITAL H
	0x4A3, // 4A3 (ң) CYRILLIC SMALL LETTER EN WITH DESCENDER == ʜ̩ [29C (ʜ) LATIN LETTER SMALL CAPITAL H,329 (◌̩) COMBINING VERTICAL LINE BELOW]
	0x4CA, // 4CA (ӊ) CYRILLIC SMALL LETTER EN WITH TAIL == ʜ̦ [29C (ʜ) LATIN LETTER SMALL CAPITAL H,326 (◌̦) COMBINING COMMA BELOW]
	0x4C8, // 4C8 (ӈ) CYRILLIC SMALL LETTER EN WITH HOOK == ʜ̦ [29C (ʜ) LATIN LETTER SMALL CAPITAL H,326 (◌̦) COMBINING COMMA BELOW]
	0x456, // 456 (і) CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I == 69 (i) LATIN SMALL LETTER I
	0xA647, // A647 (ꙇ) CYRILLIC SMALL LETTER IOTA == 69 (i) LATIN SMALL LETTER I
	0x4CF, // 4CF (ӏ) CYRILLIC SMALL LETTER PALOCHKA == 69 (i) LATIN SMALL LETTER I
	0x458, // 458 (ј) CYRILLIC SMALL LETTER JE == 6A (j) LATIN SMALL LETTER J
	0x2DE8, // 2DE8 (◌ⷨ) COMBINING CYRILLIC LETTER EM == 1DDF (◌ᷟ) COMBINING LATIN LETTER SMALL CAPITAL M
	0x438, // 438 (и) CYRILLIC SMALL LETTER I == 1D0E (ᴎ) LATIN LETTER SMALL CAPITAL REVERSED N
	0x43E, // 43E (о) CYRILLIC SMALL LETTER O == 6F (o) LATIN SMALL LETTER O
	0x4E9, // 4E9 (ө) CYRILLIC SMALL LETTER BARRED O == o̵ [6F (o) LATIN SMALL LETTER O,335 (◌̵) COMBINING SHORT STROKE OVERLAY]
	0x473, // 473 (ѳ) CYRILLIC SMALL LETTER FITA == o̵ [6F (o) LATIN SMALL LETTER O,335 (◌̵) COMBINING SHORT STROKE OVERLAY]
	0xA699, // A699 (ꚙ) CYRILLIC SMALL LETTER DOUBLE O == oo [6F (o) LATIN SMALL LETTER O,6F (o) LATIN SMALL LETTER O]
	0x440, // 440 (р) CYRILLIC SMALL LETTER ER == 70 (p) LATIN SMALL LETTER P
	0x444, // 444 (ф) CYRILLIC SMALL LETTER EF == 278 (ɸ) LATIN SMALL LETTER PHI
	0x51B, // 51B (ԛ) CYRILLIC SMALL LETTER QA == 71 (q) LATIN SMALL LETTER Q
	0x43A, // 43A (к) CYRILLIC SMALL LETTER KA == 138 (ĸ) LATIN SMALL LETTER KRA
	0x49B, // 49B (қ) CYRILLIC SMALL LETTER KA WITH DESCENDER == ĸ̩ [138 (ĸ) LATIN SMALL LETTER KRA,329 (◌̩) COMBINING VERTICAL LINE BELOW]
	0x49F, // 49F (ҟ) CYRILLIC SMALL LETTER KA WITH STROKE == ĸ̵ [138 (ĸ) LATIN SMALL LETTER KRA,335 (◌̵) COMBINING SHORT STROKE OVERLAY]
	0x433, // 433 (г) CYRILLIC SMALL LETTER GHE == 72 (r) LATIN SMALL LETTER R
	0x493, // 493 (ғ) CYRILLIC SMALL LETTER GHE WITH STROKE == r̵ [72 (r) LATIN SMALL LETTER R,335 (◌̵) COMBINING SHORT STROKE OVERLAY]
	0x491, // 491 (ґ) CYRILLIC SMALL LETTER GHE WITH UPTURN == r' [72 (r) LATIN SMALL LETTER R,27 (') APOSTROPHE]
	0x44F, // 44F (я) CYRILLIC SMALL LETTER YA == 1D19 (ᴙ) LATIN LETTER SMALL CAPITAL REVERSED R
	0x455, // 455 (ѕ) CYRILLIC SMALL LETTER DZE == 73 (s) LATIN SMALL LETTER S
	0x442, // 442 (т) CYRILLIC SMALL LETTER TE == 1D1B (ᴛ) LATIN LETTER SMALL CAPITAL T
	0x4AD, // 4AD (ҭ) CYRILLIC SMALL LETTER TE WITH DESCENDER == ᴛ̩ [1D1B (ᴛ) LATIN LETTER SMALL CAPITAL T,329 (◌̩) COMBINING VERTICAL LINE BELOW]
	0x475, // 475 (ѵ) CYRILLIC SMALL LETTER IZHITSA == 76 (v) LATIN SMALL LETTER V
	0x461, // 461 (ѡ) CYRILLIC SMALL LETTER OMEGA == 77 (w) LATIN SMALL LETTER W
	0x51D, // 51D (ԝ) CYRILLIC SMALL LETTER WE == 77 (w) LATIN SMALL LETTER W
	0x47D, // 47D (ѽ) CYRILLIC SMALL LETTER OMEGA WITH TITLO == w҆҇ [77 (w) LATIN SMALL LETTER W,486 (◌҆) COMBINING CYRILLIC PSILI PNEUMATA,487 (◌҇) COMBINING CYRILLIC POKRYTIE]
	0x43C, // 43C (м) CYRILLIC SMALL LETTER EM == 28D (ʍ) LATIN SMALL LETTER TURNED W
	0x4CE, // 4CE (ӎ) CYRILLIC SMALL LETTER EM WITH TAIL == ʍ̦ [28D (ʍ) LATIN SMALL LETTER TURNED W,326 (◌̦) COMBINING COMMA BELOW]
	0x445, // 445 (х) CYRILLIC SMALL LETTER HA == 78 (x) LATIN SMALL LETTER X
	0x2DEF, // 2DEF (◌ⷯ) COMBINING CYRILLIC LETTER HA == 36F (◌ͯ) COMBINING LATIN SMALL LETTER X
	0x443, // 443 (у) CYRILLIC SMALL LETTER U == 79 (y) LATIN SMALL LETTER Y
	0x4AF, // 4AF (ү) CYRILLIC SMALL LETTER STRAIGHT U == 79 (y) LATIN SMALL LETTER Y
	0x4B1, // 4B1 (ұ) CYRILLIC SMALL LETTER STRAIGHT U WITH STROKE == y̵ [79 (y) LATIN SMALL LETTER Y,335 (◌̵) COMBINING SHORT STROKE OVERLAY]
	0x4E1, // 4E1 (ӡ) CYRILLIC SMALL LETTER ABKHASIAN DZE == 21D (ȝ) LATIN SMALL LETTER YOGH
	0xA645, // A645 (ꙅ) CYRILLIC SMALL LETTER REVERSED DZE == 1A8 (ƨ) LATIN SMALL LETTER TONE TWO
	0x44C, // 44C (ь) CYRILLIC SMALL LETTER SOFT SIGN == 185 (ƅ) LATIN SMALL LETTER TONE SIX
	0x44B, // 44B (ы) CYRILLIC SMALL LETTER YERU == ƅi [185 (ƅ) LATIN SMALL LETTER TONE SIX,69 (i) LATIN SMALL LETTER I]
	0x43F, // 43F (п) CYRILLIC SMALL LETTER PE == 3C0 (π) GREEK SMALL LETTER PI
	0x471, // 471 (ѱ) CYRILLIC SMALL LETTER PSI == 3C8 (ψ) GREEK SMALL LETTER PSI
	0xA64D, // A64D (ꙍ) CYRILLIC SMALL LETTER BROAD OMEGA == 3C9 (ω) GREEK SMALL LETTER OMEGA
]