// created: 2022-10-24T08:28:52.043Z
// version: 15.0.0
export default [
	// "ẟ"
	// 3B4 (δ) GREEK SMALL LETTER DELTA (Grek)
	// 1577 (ᕷ) CANADIAN SYLLABICS NUNAVIK HO (Cans)
	0x56E, // 56E (ծ) ARMENIAN SMALL LETTER CA
	// "f"
	// 66 (f) LATIN SMALL LETTER F (Latn)
	0x584, // 584 (ք) ARMENIAN SMALL LETTER KEH
	// "g"
	// 67 (g) LATIN SMALL LETTER G (Latn)
	0x581, // 581 (ց) ARMENIAN SMALL LETTER CO
	// "h"
	// 68 (h) LATIN SMALL LETTER H (Latn)
	// 4BB (һ) CYRILLIC SMALL LETTER SHHA (Cyrl)
	// 13C2 (Ꮒ) CHEROKEE LETTER NI (Cher)
	0x570, // 570 (հ) ARMENIAN SMALL LETTER HO
	// "n"
	// 6E (n) LATIN SMALL LETTER N (Latn)
	0x578, // 578 (ո) ARMENIAN SMALL LETTER VO
	0x57C, // 57C (ռ) ARMENIAN SMALL LETTER RA
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// C02 (◌ం) TELUGU SIGN ANUSVARA (Telu)
	// C82 (◌ಂ) KANNADA SIGN ANUSVARA (Knda)
	// D02 (◌ം) MALAYALAM SIGN ANUSVARA (Mlym)
	// D82 (◌ං) SINHALA SIGN ANUSVARAYA (Sinh)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// A66 (੦) GURMUKHI DIGIT ZERO (Guru)
	// AE6 (૦) GUJARATI DIGIT ZERO (Gujr)
	// BE6 (௦) TAMIL DIGIT ZERO (Taml)
	// C66 (౦) TELUGU DIGIT ZERO (Telu)
	// CE6 (೦) KANNADA DIGIT ZERO (Knda)
	// D66 (൦) MALAYALAM DIGIT ZERO (Mlym)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// ED0 (໐) LAO DIGIT ZERO (Laoo)
	// 1040 (၀) MYANMAR DIGIT ZERO (Mymr)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 2C9F (ⲟ) COPTIC SMALL LETTER O (Copt)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 10FF (ჿ) GEORGIAN LETTER LABIAL SIGN (Geor)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	// D20 (ഠ) MALAYALAM LETTER TTHA (Mlym)
	// 101D (ဝ) MYANMAR LETTER WA (Mymr)
	// 104EA (𐓪) OSAGE SMALL LETTER O (Osge)
	// 118C8 (𑣈) WARANG CITI SMALL LETTER E (Wara)
	// 118D7 (𑣗) WARANG CITI SMALL LETTER BU (Wara)
	// 1042C (𐐬) DESERET SMALL LETTER LONG O (Dsrt)
	0x585, // 585 (օ) ARMENIAN SMALL LETTER OH
	// "q"
	// 71 (q) LATIN SMALL LETTER Q (Latn)
	// 51B (ԛ) CYRILLIC SMALL LETTER QA (Cyrl)
	0x563, // 563 (գ) ARMENIAN SMALL LETTER GIM
	0x566, // 566 (զ) ARMENIAN SMALL LETTER ZA
	// "u"
	// 75 (u) LATIN SMALL LETTER U (Latn)
	// 3C5 (υ) GREEK SMALL LETTER UPSILON (Grek)
	// 104F6 (𐓶) OSAGE SMALL LETTER U (Osge)
	// 118D8 (𑣘) WARANG CITI SMALL LETTER PU (Wara)
	0x57D, // 57D (ս) ARMENIAN SMALL LETTER SEH
	// "ɰ"
	// 1223 (ሣ) ETHIOPIC SYLLABLE SZAA (Ethi)
	0x57A, // 57A (պ) ARMENIAN SMALL LETTER PEH
	// "w"
	// 77 (w) LATIN SMALL LETTER W (Latn)
	// 51D (ԝ) CYRILLIC SMALL LETTER WE (Cyrl)
	// 1170A (𑜊) AHOM LETTER JA (Ahom)
	// 1170E (𑜎) AHOM LETTER LA (Ahom)
	// 1170F (𑜏) AHOM LETTER SA (Ahom)
	0x561, // 561 (ա) ARMENIAN SMALL LETTER AYB
]