// created: 2022-10-24T08:28:52.112Z
// version: 15.0.0
export default [
	// "2"
	// 32 (2) DIGIT TWO (Zyyy)
	// 14BF (ᒿ) CANADIAN SYLLABICS SAYISI M (Cans)
	0xA6EF, // A6EF (ꛯ) BAMUM LETTER KOGHOM
	// "̂"
	// 65B (◌ٛ) ARABIC VOWEL SIGN INVERTED SMALL V ABOVE (Arab)
	// 7EE (◌߮) NKO COMBINING LONG DESCENDING TONE (Nkoo)
	0xA6F0, // A6F0 (◌꛰) BAMUM COMBINING MARK KOQNDON
	// "̄"
	// 659 (◌ٙ) ARABIC ZWARAKAY (Arab)
	// 7EB (◌߫) NKO COMBINING SHORT HIGH TONE (Nkoo)
	0xA6F1, // A6F1 (◌꛱) BAMUM COMBINING MARK TUKWENTIS
	// "?"
	// 13AE (Ꭾ) CHEROKEE LETTER HE (Cher)
	0xA6EB, // A6EB (ꛫ) BAMUM LETTER NTUU
	// "Ⱶ"
	// 13A8 (Ꭸ) CHEROKEE LETTER GE (Cher)
	// 13B0 (Ꮀ) CHEROKEE LETTER HO (Cher)
	0xA6B1, // A6B1 (ꚱ) BAMUM LETTER NDAA
	// "V"
	// 667 (٧) ARABIC-INDIC DIGIT SEVEN (Arab)
	// 2D38 (ⴸ) TIFINAGH LETTER YADH (Tfng)
	// 13D9 (Ꮩ) CHEROKEE LETTER DO (Cher)
	// 142F (ᐯ) CANADIAN SYLLABICS PE (Cans)
	// A4E6 (ꓦ) LISU LETTER HA (Lisu)
	// 16F08 (𖼈) MIAO LETTER VA (Plrd)
	// 1051D (𐔝) ELBASAN LETTER TE (Elba)
	0xA6DF, // A6DF (ꛟ) BAMUM LETTER KO
	// "Ʌ"
	// 668 (٨) ARABIC-INDIC DIGIT EIGHT (Arab)
	// 2D37 (ⴷ) TIFINAGH LETTER YAD (Tfng)
	// 1431 (ᐱ) CANADIAN SYLLABICS PI (Cans)
	// A4E5 (ꓥ) LISU LETTER NGA (Lisu)
	// 16F3D (𖼽) MIAO LETTER ZZA (Plrd)
	// 1028D (𐊍) LYCIAN LETTER L (Lyci)
	0xA6CE, // A6CE (ꛎ) BAMUM LETTER MI
	// "Π"
	// 220F (∏) N-ARY PRODUCT (Zyyy)
	0xA6DB, // A6DB (ꛛ) BAMUM LETTER NA
	// "ᚹ"
	// 16B9 (ᚹ) RUNIC LETTER WUNJO WYNN W (Runr)
	0xA6B0, // A6B0 (ꚰ) BAMUM LETTER TAA
]