// created: 2022-10-24T08:28:52.226Z
// version: 15.0.0
export default [
	// "4"
	// 34 (4) DIGIT FOUR (Zyyy)
	0x13CE, // 13CE (Ꮞ) CHEROKEE LETTER SE
	// "6"
	// 36 (6) DIGIT SIX (Zyyy)
	// 431 (б) CYRILLIC SMALL LETTER BE (Cyrl)
	// 118D5 (𑣕) WARANG CITI SMALL LETTER AT (Wara)
	0x13EE, // 13EE (Ꮾ) CHEROKEE LETTER WV
	// "?"
	// A6EB (ꛫ) BAMUM LETTER NTUU (Bamu)
	0x13AE, // 13AE (Ꭾ) CHEROKEE LETTER HE
	// "A"
	// 15C5 (ᗅ) CANADIAN SYLLABICS CARRIER GHO (Cans)
	// A4EE (ꓮ) LISU LETTER A (Lisu)
	// 16F40 (𖽀) MIAO LETTER ZZYA (Plrd)
	// 102A0 (𐊠) CARIAN LETTER A (Cari)
	0x13AA, // 13AA (Ꭺ) CHEROKEE LETTER GO
	// "b"
	// 62 (b) LATIN SMALL LETTER B (Latn)
	// 1472 (ᑲ) CANADIAN SYLLABICS KA (Cans)
	// 15AF (ᖯ) CANADIAN SYLLABICS AIVILIK B (Cans)
	0x13CF, // 13CF (Ꮟ) CHEROKEE LETTER SI
	// "B"
	// 15F7 (ᗷ) CANADIAN SYLLABICS CARRIER KHE (Cans)
	// A4D0 (ꓐ) LISU LETTER BA (Lisu)
	// 10282 (𐊂) LYCIAN LETTER B (Lyci)
	// 102A1 (𐊡) CARIAN LETTER P2 (Cari)
	// 10301 (𐌁) OLD ITALIC LETTER BE (Ital)
	0x13F4, // 13F4 (Ᏼ) CHEROKEE LETTER YV
	// "C"
	// 118F2 (𑣲) WARANG CITI NUMBER NINETY (Wara)
	// 118E9 (𑣩) WARANG CITI DIGIT NINE (Wara)
	// A4DA (ꓚ) LISU LETTER CA (Lisu)
	// 102A2 (𐊢) CARIAN LETTER D (Cari)
	// 10302 (𐌂) OLD ITALIC LETTER KE (Ital)
	// 1051C (𐔜) ELBASAN LETTER SHE (Elba)
	0x13DF, // 13DF (Ꮯ) CHEROKEE LETTER TLI
	// "d"
	// 64 (d) LATIN SMALL LETTER D (Latn)
	// 146F (ᑯ) CANADIAN SYLLABICS KO (Cans)
	// A4D2 (ꓒ) LISU LETTER PHA (Lisu)
	0x13E7, // 13E7 (Ꮷ) CHEROKEE LETTER TSU
	// "D"
	// 15DE (ᗞ) CANADIAN SYLLABICS CARRIER THE (Cans)
	// 15EA (ᗪ) CANADIAN SYLLABICS CARRIER PE (Cans)
	// A4D3 (ꓓ) LISU LETTER DA (Lisu)
	0x13A0, // 13A0 (Ꭰ) CHEROKEE LETTER A
	// "E"
	// 2D39 (ⴹ) TIFINAGH LETTER YADD (Tfng)
	// A4F0 (ꓰ) LISU LETTER E (Lisu)
	// 10286 (𐊆) LYCIAN LETTER I (Lyci)
	0x13AC, // 13AC (Ꭼ) CHEROKEE LETTER GV
	// "Ɛ"
	// 16F2D (𖼭) MIAO LETTER NYHA (Plrd)
	0x13CB, // 13CB (Ꮛ) CHEROKEE LETTER QUV
	// "G"
	// A4D6 (ꓖ) LISU LETTER GA (Lisu)
	0x13C0, // 13C0 (Ꮐ) CHEROKEE LETTER NAH
	0x13F3, // 13F3 (Ᏻ) CHEROKEE LETTER YU
	// "h"
	// 68 (h) LATIN SMALL LETTER H (Latn)
	// 4BB (һ) CYRILLIC SMALL LETTER SHHA (Cyrl)
	// 570 (հ) ARMENIAN SMALL LETTER HO (Armn)
	0x13C2, // 13C2 (Ꮒ) CHEROKEE LETTER NI
	// "H"
	// 157C (ᕼ) CANADIAN SYLLABICS NUNAVUT H (Cans)
	// A4E7 (ꓧ) LISU LETTER XA (Lisu)
	// 102CF (𐋏) CARIAN LETTER E2 (Cari)
	0x13BB, // 13BB (Ꮋ) CHEROKEE LETTER MI
	// "Ⱶ"
	// A6B1 (ꚱ) BAMUM LETTER NDAA (Bamu)
	0x13A8, // 13A8 (Ꭸ) CHEROKEE LETTER GE
	0x13B0, // 13B0 (Ꮀ) CHEROKEE LETTER HO
	// "i"
	// 69 (i) LATIN SMALL LETTER I (Latn)
	// 3B9 (ι) GREEK SMALL LETTER IOTA (Grek)
	// 456 (і) CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I (Cyrl)
	// 4CF (ӏ) CYRILLIC SMALL LETTER PALOCHKA (Cyrl)
	// 118C3 (𑣃) WARANG CITI SMALL LETTER YU (Wara)
	0x13A5, // 13A5 (Ꭵ) CHEROKEE LETTER V
	// "J"
	// 148D (ᒍ) CANADIAN SYLLABICS CO (Cans)
	// A4D9 (ꓙ) LISU LETTER JA (Lisu)
	0x13AB, // 13AB (Ꭻ) CHEROKEE LETTER GU
	// "K"
	// 16D5 (ᛕ) RUNIC LETTER OPEN-P (Runr)
	// A4D7 (ꓗ) LISU LETTER KA (Lisu)
	// 10518 (𐔘) ELBASAN LETTER QE (Elba)
	0x13E6, // 13E6 (Ꮶ) CHEROKEE LETTER TSO
	// "L"
	// 14AA (ᒪ) CANADIAN SYLLABICS MA (Cans)
	// A4E1 (ꓡ) LISU LETTER LA (Lisu)
	// 16F16 (𖼖) MIAO LETTER LA (Plrd)
	// 10526 (𐔦) ELBASAN LETTER GHAMMA (Elba)
	0x13DE, // 13DE (Ꮮ) CHEROKEE LETTER TLE
	// "M"
	// 15F0 (ᗰ) CANADIAN SYLLABICS CARRIER GO (Cans)
	// 16D6 (ᛖ) RUNIC LETTER EHWAZ EH E (Runr)
	// A4DF (ꓟ) LISU LETTER MA (Lisu)
	// 102B0 (𐊰) CARIAN LETTER S (Cari)
	// 10311 (𐌑) OLD ITALIC LETTER SHE (Ital)
	0x13B7, // 13B7 (Ꮇ) CHEROKEE LETTER LU
	// "O̵"
	// 3B8 (θ) GREEK SMALL LETTER THETA (Grek)
	// 2D31 (ⴱ) TIFINAGH LETTER YAB (Tfng)
	0x13BE, // 13BE (Ꮎ) CHEROKEE LETTER NA
	0x13EB, // 13EB (Ꮻ) CHEROKEE LETTER WI
	// "P"
	// 146D (ᑭ) CANADIAN SYLLABICS KI (Cans)
	// A4D1 (ꓑ) LISU LETTER PA (Lisu)
	// 10295 (𐊕) LYCIAN LETTER R (Lyci)
	0x13E2, // 13E2 (Ꮲ) CHEROKEE LETTER TLV
	// "R"
	// 1587 (ᖇ) CANADIAN SYLLABICS TLHI (Cans)
	// A4E3 (ꓣ) LISU LETTER ZHA (Lisu)
	// 16F35 (𖼵) MIAO LETTER ZHA (Plrd)
	0x13A1, // 13A1 (Ꭱ) CHEROKEE LETTER E
	0x13D2, // 13D2 (Ꮢ) CHEROKEE LETTER SV
	// "S"
	// A4E2 (ꓢ) LISU LETTER SA (Lisu)
	// 16F3A (𖼺) MIAO LETTER SA (Plrd)
	// 10296 (𐊖) LYCIAN LETTER S (Lyci)
	0x13D5, // 13D5 (Ꮥ) CHEROKEE LETTER DE
	0x13DA, // 13DA (Ꮪ) CHEROKEE LETTER DU
	// "ß"
	// DF (ß) LATIN SMALL LETTER SHARP S (Latn)
	// 3B2 (β) GREEK SMALL LETTER BETA (Grek)
	0x13F0, // 13F0 (Ᏸ) CHEROKEE LETTER YE
	// "T"
	// A4D4 (ꓔ) LISU LETTER TA (Lisu)
	// 16F0A (𖼊) MIAO LETTER TA (Plrd)
	// 10297 (𐊗) LYCIAN LETTER T (Lyci)
	// 102B1 (𐊱) CARIAN LETTER C-18 (Cari)
	// 10315 (𐌕) OLD ITALIC LETTER TE (Ital)
	0x13A2, // 13A2 (Ꭲ) CHEROKEE LETTER I
	// "V"
	// 667 (٧) ARABIC-INDIC DIGIT SEVEN (Arab)
	// 2D38 (ⴸ) TIFINAGH LETTER YADH (Tfng)
	// 142F (ᐯ) CANADIAN SYLLABICS PE (Cans)
	// A6DF (ꛟ) BAMUM LETTER KO (Bamu)
	// A4E6 (ꓦ) LISU LETTER HA (Lisu)
	// 16F08 (𖼈) MIAO LETTER VA (Plrd)
	// 1051D (𐔝) ELBASAN LETTER TE (Elba)
	0x13D9, // 13D9 (Ꮩ) CHEROKEE LETTER DO
	// "W"
	// 118EF (𑣯) WARANG CITI NUMBER SIXTY (Wara)
	// 118E6 (𑣦) WARANG CITI DIGIT SIX (Wara)
	// A4EA (ꓪ) LISU LETTER WA (Lisu)
	0x13B3, // 13B3 (Ꮃ) CHEROKEE LETTER LA
	0x13D4, // 13D4 (Ꮤ) CHEROKEE LETTER TA
	// "Y"
	// A4EC (ꓬ) LISU LETTER YA (Lisu)
	// 16F43 (𖽃) MIAO LETTER AH (Plrd)
	// 102B2 (𐊲) CARIAN LETTER U (Cari)
	0x13A9, // 13A9 (Ꭹ) CHEROKEE LETTER GI
	0x13BD, // 13BD (Ꮍ) CHEROKEE LETTER MU
	// "Z"
	// 118E5 (𑣥) WARANG CITI DIGIT FIVE (Wara)
	// A4DC (ꓜ) LISU LETTER DZA (Lisu)
	0x13C3, // 13C3 (Ꮓ) CHEROKEE LETTER NO
	// "Γ"
	// 14A5 (ᒥ) CANADIAN SYLLABICS MI (Cans)
	// 16F07 (𖼇) MIAO LETTER FA (Plrd)
	0x13B1, // 13B1 (Ꮁ) CHEROKEE LETTER HU
	// "Ѡ"
	// 15EF (ᗯ) CANADIAN SYLLABICS CARRIER GU (Cans)
	0x13C7, // 13C7 (Ꮗ) CHEROKEE LETTER QUE
]