// created: 2022-10-24T08:28:51.904Z
// version: 15.0.0
export default [
	// "9"
	// 39 (9) DIGIT NINE (Zyyy)
	// A67 (੧) GURMUKHI DIGIT ONE (Guru)
	// B68 (୨) ORIYA DIGIT TWO (Orya)
	// 9ED (৭) BENGALI DIGIT SEVEN (Beng)
	// 118CC (𑣌) WARANG CITI SMALL LETTER KO (Wara)
	// 118D6 (𑣖) WARANG CITI SMALL LETTER AM (Wara)
	0xD6D, // D6D (൭) MALAYALAM DIGIT SEVEN
	// "ঃ"
	// 983 (◌ঃ) BENGALI SIGN VISARGA (Beng)
	// A03 (◌ਃ) GURMUKHI SIGN VISARGA (Guru)
	// C03 (◌ః) TELUGU SIGN VISARGA (Telu)
	// C83 (◌ಃ) KANNADA SIGN VISARGA (Knda)
	// D83 (◌ඃ) SINHALA SIGN VISARGAYA (Sinh)
	// 1038 (◌း) MYANMAR SIGN VISARGA (Mymr)
	// 114C1 (◌𑓁) TIRHUTA SIGN VISARGA (Tirh)
	0xD03, // D03 (◌ഃ) MALAYALAM SIGN VISARGA
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// C02 (◌ం) TELUGU SIGN ANUSVARA (Telu)
	// C82 (◌ಂ) KANNADA SIGN ANUSVARA (Knda)
	// D82 (◌ං) SINHALA SIGN ANUSVARAYA (Sinh)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// A66 (੦) GURMUKHI DIGIT ZERO (Guru)
	// AE6 (૦) GUJARATI DIGIT ZERO (Gujr)
	// BE6 (௦) TAMIL DIGIT ZERO (Taml)
	// C66 (౦) TELUGU DIGIT ZERO (Telu)
	// CE6 (೦) KANNADA DIGIT ZERO (Knda)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// ED0 (໐) LAO DIGIT ZERO (Laoo)
	// 1040 (၀) MYANMAR DIGIT ZERO (Mymr)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 2C9F (ⲟ) COPTIC SMALL LETTER O (Copt)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 10FF (ჿ) GEORGIAN LETTER LABIAL SIGN (Geor)
	// 585 (օ) ARMENIAN SMALL LETTER OH (Armn)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	// 101D (ဝ) MYANMAR LETTER WA (Mymr)
	// 104EA (𐓪) OSAGE SMALL LETTER O (Osge)
	// 118C8 (𑣈) WARANG CITI SMALL LETTER E (Wara)
	// 118D7 (𑣗) WARANG CITI SMALL LETTER BU (Wara)
	// 1042C (𐐬) DESERET SMALL LETTER LONG O (Dsrt)
	0xD02, // D02 (◌ം) MALAYALAM SIGN ANUSVARA
	0xD66, // D66 (൦) MALAYALAM DIGIT ZERO
	0xD20, // D20 (ഠ) MALAYALAM LETTER TTHA
	// "உ"
	// B89 (உ) TAMIL LETTER U (Taml)
	// BE8 (௨) TAMIL DIGIT TWO (Taml)
	0xD09, // D09 (ഉ) MALAYALAM LETTER U
	// "உൗ"
	// B89 (உ) TAMIL LETTER U + D57 (◌ൗ) MALAYALAM AU LENGTH MARK (Taml,Mlym)
	0xD0A, // D0A (ഊ) MALAYALAM LETTER UU
	// "ஐ"
	// B90 (ஐ) TAMIL LETTER AI (Taml)
	// B9C (ஜ) TAMIL LETTER JA (Taml)
	0xD1C, // D1C (ജ) MALAYALAM LETTER JA
	// "டி"
	// B9F (ட) TAMIL LETTER TTA + BBF (◌ி) TAMIL VOWEL SIGN I (Taml)
	0xD3A, // D3A (ഺ) MALAYALAM LETTER TTTA
	// "ண"
	// BA3 (ண) TAMIL LETTER NNA (Taml)
	0xD23, // D23 (ണ) MALAYALAM LETTER NNA
	// "ழ"
	// BB4 (ழ) TAMIL LETTER LLLA (Taml)
	0xD34, // D34 (ഴ) MALAYALAM LETTER LLLA
	// "ஶ"
	// BB6 (ஶ) TAMIL LETTER SHA (Taml)
	0xD36, // D36 (ശ) MALAYALAM LETTER SHA
	// "ி"
	// BBF (◌ி) TAMIL VOWEL SIGN I (Taml)
	0xD3F, // D3F (◌ി) MALAYALAM VOWEL SIGN I
	0xD40, // D40 (◌ീ) MALAYALAM VOWEL SIGN II
]