// created: 2022-10-24T08:28:51.975Z
// version: 15.0.0
export default [
	// "̊"
	// 5AF (◌֯) HEBREW MARK MASORA CIRCLE (Hebr)
	// 6DF (◌۟) ARABIC SMALL HIGH ROUNDED ZERO (Arab)
	// 652 (◌ْ) ARABIC SUKUN (Arab)
	// B82 (◌ஂ) TAMIL SIGN ANUSVARA (Taml)
	// 17C6 (◌ំ) KHMER SIGN NIKAHIT (Khmr)
	// 11300 (◌𑌀) GRANTHA SIGN COMBINING ANUSVARA ABOVE (Gran)
	// E4D (◌ํ) THAI CHARACTER NIKHAHIT (Thai)
	// ECD (◌ໍ) LAO NIGGAHITA (Laoo)
	0x1036, // 1036 (◌ံ) MYANMAR SIGN ANUSVARA
	// "ঃ"
	// 983 (◌ঃ) BENGALI SIGN VISARGA (Beng)
	// A03 (◌ਃ) GURMUKHI SIGN VISARGA (Guru)
	// C03 (◌ః) TELUGU SIGN VISARGA (Telu)
	// C83 (◌ಃ) KANNADA SIGN VISARGA (Knda)
	// D03 (◌ഃ) MALAYALAM SIGN VISARGA (Mlym)
	// D83 (◌ඃ) SINHALA SIGN VISARGAYA (Sinh)
	// 114C1 (◌𑓁) TIRHUTA SIGN VISARGA (Tirh)
	0x1038, // 1038 (◌း) MYANMAR SIGN VISARGA
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// C02 (◌ం) TELUGU SIGN ANUSVARA (Telu)
	// C82 (◌ಂ) KANNADA SIGN ANUSVARA (Knda)
	// D02 (◌ം) MALAYALAM SIGN ANUSVARA (Mlym)
	// D82 (◌ං) SINHALA SIGN ANUSVARAYA (Sinh)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// A66 (੦) GURMUKHI DIGIT ZERO (Guru)
	// AE6 (૦) GUJARATI DIGIT ZERO (Gujr)
	// BE6 (௦) TAMIL DIGIT ZERO (Taml)
	// C66 (౦) TELUGU DIGIT ZERO (Telu)
	// CE6 (೦) KANNADA DIGIT ZERO (Knda)
	// D66 (൦) MALAYALAM DIGIT ZERO (Mlym)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// ED0 (໐) LAO DIGIT ZERO (Laoo)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 2C9F (ⲟ) COPTIC SMALL LETTER O (Copt)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 10FF (ჿ) GEORGIAN LETTER LABIAL SIGN (Geor)
	// 585 (օ) ARMENIAN SMALL LETTER OH (Armn)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	// D20 (ഠ) MALAYALAM LETTER TTHA (Mlym)
	// 104EA (𐓪) OSAGE SMALL LETTER O (Osge)
	// 118C8 (𑣈) WARANG CITI SMALL LETTER E (Wara)
	// 118D7 (𑣗) WARANG CITI SMALL LETTER BU (Wara)
	// 1042C (𐐬) DESERET SMALL LETTER LONG O (Dsrt)
	0x1040, // 1040 (၀) MYANMAR DIGIT ZERO
	0x101D, // 101D (ဝ) MYANMAR LETTER WA
	// "oာ"
	// 6F (o) LATIN SMALL LETTER O + 102C (◌ာ) MYANMAR VOWEL SIGN AA (Latn,Mymr)
	0x1010, // 1010 (တ) MYANMAR LETTER TA
]