// created: 2022-10-24T08:28:52.543Z
// version: 15.0.0
export default [
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// C02 (◌ం) TELUGU SIGN ANUSVARA (Telu)
	// C82 (◌ಂ) KANNADA SIGN ANUSVARA (Knda)
	// D02 (◌ം) MALAYALAM SIGN ANUSVARA (Mlym)
	// D82 (◌ං) SINHALA SIGN ANUSVARAYA (Sinh)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// A66 (੦) GURMUKHI DIGIT ZERO (Guru)
	// AE6 (૦) GUJARATI DIGIT ZERO (Gujr)
	// BE6 (௦) TAMIL DIGIT ZERO (Taml)
	// C66 (౦) TELUGU DIGIT ZERO (Telu)
	// CE6 (೦) KANNADA DIGIT ZERO (Knda)
	// D66 (൦) MALAYALAM DIGIT ZERO (Mlym)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// ED0 (໐) LAO DIGIT ZERO (Laoo)
	// 1040 (၀) MYANMAR DIGIT ZERO (Mymr)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 2C9F (ⲟ) COPTIC SMALL LETTER O (Copt)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 10FF (ჿ) GEORGIAN LETTER LABIAL SIGN (Geor)
	// 585 (օ) ARMENIAN SMALL LETTER OH (Armn)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	// D20 (ഠ) MALAYALAM LETTER TTHA (Mlym)
	// 101D (ဝ) MYANMAR LETTER WA (Mymr)
	// 118C8 (𑣈) WARANG CITI SMALL LETTER E (Wara)
	// 118D7 (𑣗) WARANG CITI SMALL LETTER BU (Wara)
	// 1042C (𐐬) DESERET SMALL LETTER LONG O (Dsrt)
	0x104EA, // 104EA (𐓪) OSAGE SMALL LETTER O
	// "u"
	// 75 (u) LATIN SMALL LETTER U (Latn)
	// 3C5 (υ) GREEK SMALL LETTER UPSILON (Grek)
	// 57D (ս) ARMENIAN SMALL LETTER SEH (Armn)
	// 118D8 (𑣘) WARANG CITI SMALL LETTER PU (Wara)
	0x104F6, // 104F6 (𐓶) OSAGE SMALL LETTER U
	// "λ"
	// 3BB (λ) GREEK SMALL LETTER LAMDA (Grek)
	0x104DB, // 104DB (𐓛) OSAGE SMALL LETTER AH
	// "ψ"
	// 3C8 (ψ) GREEK SMALL LETTER PSI (Grek)
	0x104F9, // 104F9 (𐓹) OSAGE SMALL LETTER GHA
]