// created: 2022-10-24T08:40:32.834Z
// version: 15.0.0
export default [
	// "́"
	// 59C (◌֜) HEBREW ACCENT GERESH (Hebr)
	// 59D (◌֝) HEBREW ACCENT GERESH MUQDAM (Hebr)
	//0x618, // 618 (◌ؘ) ARABIC SMALL FATHA
	//0x64E, // 64E (◌َ) ARABIC FATHA
	// "̆̇"
	// 901 (◌ँ) DEVANAGARI SIGN CANDRABINDU (Deva)
	//0x6E8, // 6E8 (◌ۨ) ARABIC SMALL HIGH NOON
	// "̊"
	// 5AF (◌֯) HEBREW MARK MASORA CIRCLE (Hebr)
	// E4D (◌ํ) THAI CHARACTER NIKHAHIT (Thai)
	//0x6DF, // 6DF (◌۟) ARABIC SMALL HIGH ROUNDED ZERO
	//0x652, // 652 (◌ْ) ARABIC SUKUN
	// "̇"
	// 5C4 (◌ׄ) HEBREW MARK UPPER DOT (Hebr)
	// 5B9 (◌ֹ) HEBREW POINT HOLAM (Hebr)
	// 5BA (◌ֺ) HEBREW POINT HOLAM HASER FOR VAV (Hebr)
	// 5C2 (◌ׂ) HEBREW POINT SIN DOT (Hebr)
	// 5C1 (◌ׁ) HEBREW POINT SHIN DOT (Hebr)
	// 902 (◌ं) DEVANAGARI SIGN ANUSVARA (Deva)
	//0x6EC, // 6EC (◌۬) ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE
	//0x8EA, // 8EA (◌࣪) ARABIC TONE ONE DOT ABOVE
	// "̣"
	// 5B4 (◌ִ) HEBREW POINT HIRIQ (Hebr)
	// 93C (◌़) DEVANAGARI SIGN NUKTA (Deva)
	//0x8ED, // 8ED (◌࣭) ARABIC TONE ONE DOT BELOW
	//0x65C, // 65C (◌ٜ) ARABIC VOWEL SIGN DOT BELOW
	// "l"
	// 6C (l) LATIN SMALL LETTER L (Latn)
	// 5D5 (ו) HEBREW LETTER VAV (Hebr)
	// 5DF (ן) HEBREW LETTER FINAL NUN (Hebr)
	//0x661, // 661 (١) ARABIC-INDIC DIGIT ONE (20221025: changed)
	0x627, // 627 (ا) ARABIC LETTER ALEF
	// "lٕ"
	// 6C (l) LATIN SMALL LETTER L + 655 (◌ٕ) ARABIC HAMZA BELOW (Latn,Arab)
	0x625, // 625 (إ) ARABIC LETTER ALEF WITH HAMZA BELOW
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	//0x665, // 665 (٥) ARABIC-INDIC DIGIT FIVE (20221025: changed)
	//0x6F5, // 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (20221025: changed)
	0x647, // 647 (ه) ARABIC LETTER HEH
	0x6BE, // 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE
	0x6C1, // 6C1 (ہ) ARABIC LETTER HEH GOAL
	0x6D5, // 6D5 (ە) ARABIC LETTER AE
	// "ô"
	// 6F (o) LATIN SMALL LETTER O + 302 (◌̂) COMBINING CIRCUMFLEX ACCENT (Latn,Zinh)
	0x6FF, // 6FF (ۿ) ARABIC LETTER HEH WITH INVERTED V
	// "ة"
	// F6 (ö) LATIN SMALL LETTER O WITH DIAERESIS (Latn)
	0x6C3, // 6C3 (ۃ) ARABIC LETTER TEH MARBUTA GOAL
]