// created: 2022-10-24T08:40:32.787Z
// version: 15.0.0
export default [
	// "a"
	// 61 (a) LATIN SMALL LETTER A (Latn)
	// 3B1 (α) GREEK SMALL LETTER ALPHA (Grek)
	0x430, // 430 (а) CYRILLIC SMALL LETTER A
	// "ae"
	// 61 (a) LATIN SMALL LETTER A + 65 (e) LATIN SMALL LETTER E (Latn)
	// E6 (æ) LATIN SMALL LETTER AE (Latn)
	0x4D5, // 4D5 (ӕ) CYRILLIC SMALL LIGATURE A IE
	// "c"
	// 63 (c) LATIN SMALL LETTER C (Latn)
	0x441, // 441 (с) CYRILLIC SMALL LETTER ES
	// "c̦"
	// E7 (ç) LATIN SMALL LETTER C WITH CEDILLA (Latn)
	0x4AB, // 4AB (ҫ) CYRILLIC SMALL LETTER ES WITH DESCENDER
	// "ꞓ"
	// 3B5 (ε) GREEK SMALL LETTER EPSILON (Grek)
	0x454, // 454 (є) CYRILLIC SMALL LETTER UKRAINIAN IE
	// "e"
	// 65 (e) LATIN SMALL LETTER E (Latn)
	0x435, // 435 (е) CYRILLIC SMALL LETTER IE
	0x4BD, // 4BD (ҽ) CYRILLIC SMALL LETTER ABKHASIAN CHE
	// "h"
	// 68 (h) LATIN SMALL LETTER H (Latn)
	0x4BB, // 4BB (һ) CYRILLIC SMALL LETTER SHHA
	// "i"
	// 69 (i) LATIN SMALL LETTER I (Latn)
	// 3B9 (ι) GREEK SMALL LETTER IOTA (Grek)
	0x456, // 456 (і) CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
	0x4CF, // 4CF (ӏ) CYRILLIC SMALL LETTER PALOCHKA
	// "j"
	// 6A (j) LATIN SMALL LETTER J (Latn)
	0x458, // 458 (ј) CYRILLIC SMALL LETTER JE
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	0x43E, // 43E (о) CYRILLIC SMALL LETTER O
	// "p"
	// 70 (p) LATIN SMALL LETTER P (Latn)
	// 3C1 (ρ) GREEK SMALL LETTER RHO (Grek)
	0x440, // 440 (р) CYRILLIC SMALL LETTER ER
	// "ɸ"
	// 3C6 (φ) GREEK SMALL LETTER PHI (Grek)
	0x444, // 444 (ф) CYRILLIC SMALL LETTER EF
	// "q"
	// 71 (q) LATIN SMALL LETTER Q (Latn)
	0x51B, // 51B (ԛ) CYRILLIC SMALL LETTER QA
	// "ĸ"
	// 3BA (κ) GREEK SMALL LETTER KAPPA (Grek)
	0x43A, // 43A (к) CYRILLIC SMALL LETTER KA
	// "r"
	// 72 (r) LATIN SMALL LETTER R (Latn)
	0x433, // 433 (г) CYRILLIC SMALL LETTER GHE
	// "s"
	// 73 (s) LATIN SMALL LETTER S (Latn)
	0x455, // 455 (ѕ) CYRILLIC SMALL LETTER DZE
	// "ᴛ"
	// 3C4 (τ) GREEK SMALL LETTER TAU (Grek)
	0x442, // 442 (т) CYRILLIC SMALL LETTER TE
	// "w"
	// 77 (w) LATIN SMALL LETTER W (Latn)
	0x51D, // 51D (ԝ) CYRILLIC SMALL LETTER WE
	// "x"
	// 78 (x) LATIN SMALL LETTER X (Latn)
	0x445, // 445 (х) CYRILLIC SMALL LETTER HA
	// "y"
	// 79 (y) LATIN SMALL LETTER Y (Latn)
	// 3B3 (γ) GREEK SMALL LETTER GAMMA (Grek)
	0x443, // 443 (у) CYRILLIC SMALL LETTER U
	0x4AF, // 4AF (ү) CYRILLIC SMALL LETTER STRAIGHT U
]