// created: 2022-10-24T08:40:32.858Z
// version: 15.0.0
export default [
	// "̆̇"
	// 6E8 (◌ۨ) ARABIC SMALL HIGH NOON (Arab)
	//0x901, // 901 (◌ँ) DEVANAGARI SIGN CANDRABINDU
	// "̇"
	// 5C4 (◌ׄ) HEBREW MARK UPPER DOT (Hebr)
	// 6EC (◌۬) ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE (Arab)
	// 8EA (◌࣪) ARABIC TONE ONE DOT ABOVE (Arab)
	// 5B9 (◌ֹ) HEBREW POINT HOLAM (Hebr)
	// 5BA (◌ֺ) HEBREW POINT HOLAM HASER FOR VAV (Hebr)
	// 5C2 (◌ׂ) HEBREW POINT SIN DOT (Hebr)
	// 5C1 (◌ׁ) HEBREW POINT SHIN DOT (Hebr)
	//0x902, // 902 (◌ं) DEVANAGARI SIGN ANUSVARA
	// "̣"
	// 8ED (◌࣭) ARABIC TONE ONE DOT BELOW (Arab)
	// 5B4 (◌ִ) HEBREW POINT HIRIQ (Hebr)
	// 65C (◌ٜ) ARABIC VOWEL SIGN DOT BELOW (Arab)
	//0x93C, // 93C (◌़) DEVANAGARI SIGN NUKTA
	// "٩"
	// 669 (٩) ARABIC-INDIC DIGIT NINE (Arab)
	//0x967, // 967 (१) DEVANAGARI DIGIT ONE (20221025: changed)
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 3BF (ο) GREEK SMALL LETTER OMICRON (Grek)
	// 3C3 (σ) GREEK SMALL LETTER SIGMA (Grek)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	//0x966, // 966 (०) DEVANAGARI DIGIT ZERO (20221025: changed)
]