export default [
	// computed: 2022-10-15T05:22:41.091Z
	// version: 15.0.0
	// "j"
	// 6A (j) LATIN SMALL LETTER J (Latn)
	0x3F3, // 3F3 (ϳ) GREEK LETTER YOT
	// "r"
	// 72 (r) LATIN SMALL LETTER R (Latn)
	0x1D26, // 1D26 (ᴦ) GREEK LETTER SMALL CAPITAL GAMMA
	
	// "a"
	// 61 (a) LATIN SMALL LETTER A (Latn)
	// 430 (а) CYRILLIC SMALL LETTER A (Cyrl)
	0x3B1, // 3B1 (α) GREEK SMALL LETTER ALPHA
	// "ꞓ"
	// 454 (є) CYRILLIC SMALL LETTER UKRAINIAN IE (Cyrl)
	// 511 (ԑ) CYRILLIC SMALL LETTER REVERSED ZE (Cyrl)
	0x3B5, // 3B5 (ε) GREEK SMALL LETTER EPSILON
	// "i"
	// 69 (i) LATIN SMALL LETTER I (Latn)
	// 456 (і) CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I (Cyrl)
	// 4CF (ӏ) CYRILLIC SMALL LETTER PALOCHKA (Cyrl)
	0x3B9, // 3B9 (ι) GREEK SMALL LETTER IOTA
	// "o"
	// 6F (o) LATIN SMALL LETTER O (Latn)
	// 966 (०) DEVANAGARI DIGIT ZERO (Deva)
	// E50 (๐) THAI DIGIT ZERO (Thai)
	// 665 (٥) ARABIC-INDIC DIGIT FIVE (Arab)
	// 6F5 (۵) EXTENDED ARABIC-INDIC DIGIT FIVE (Arab)
	// 43E (о) CYRILLIC SMALL LETTER O (Cyrl)
	// 5E1 (ס) HEBREW LETTER SAMEKH (Hebr)
	// 647 (ه) ARABIC LETTER HEH (Arab)
	// 6BE (ھ) ARABIC LETTER HEH DOACHASHMEE (Arab)
	// 6C1 (ہ) ARABIC LETTER HEH GOAL (Arab)
	// 6D5 (ە) ARABIC LETTER AE (Arab)
	0x3BF, // 3BF (ο) GREEK SMALL LETTER OMICRON
	0x3C3, // 3C3 (σ) GREEK SMALL LETTER SIGMA
	// "p"
	// 70 (p) LATIN SMALL LETTER P (Latn)
	// 440 (р) CYRILLIC SMALL LETTER ER (Cyrl)
	0x3C1, // 3C1 (ρ) GREEK SMALL LETTER RHO
	// "ɸ"
	// 444 (ф) CYRILLIC SMALL LETTER EF (Cyrl)
	0x3C6, // 3C6 (φ) GREEK SMALL LETTER PHI
	// "ĸ"
	// 43A (к) CYRILLIC SMALL LETTER KA (Cyrl)
	0x3BA, // 3BA (κ) GREEK SMALL LETTER KAPPA
	// "ß"
	// DF (ß) LATIN SMALL LETTER SHARP S (Latn)
	0x3B2, // 3B2 (β) GREEK SMALL LETTER BETA
	// "ᴛ"
	// 442 (т) CYRILLIC SMALL LETTER TE (Cyrl)
	0x3C4, // 3C4 (τ) GREEK SMALL LETTER TAU
	// "u"
	// 75 (u) LATIN SMALL LETTER U (Latn)
	0x3C5, // 3C5 (υ) GREEK SMALL LETTER UPSILON
	// "v"
	// 76 (v) LATIN SMALL LETTER V (Latn)
	// 5D8 (ט) HEBREW LETTER TET (Hebr)
	0x3BD, // 3BD (ν) GREEK SMALL LETTER NU
	// "y"
	// 79 (y) LATIN SMALL LETTER Y (Latn)
	// 443 (у) CYRILLIC SMALL LETTER U (Cyrl)
	// 4AF (ү) CYRILLIC SMALL LETTER STRAIGHT U (Cyrl)
	0x3B3, // 3B3 (γ) GREEK SMALL LETTER GAMMA
]